name: 'kombit_kommune'
version: '1.0.0'
config-version: 2

profile: 'kombit'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  kombit_kommune:
    staging:
      +materialized: view
      +schema: STAGING
    marts:
      copenhagen:
        +materialized: table
        +schema: COPENHAGEN
      aarhus:
        +materialized: table
        +schema: AARHUS
      odense:
        +materialized: table
        +schema: ODENSE
      aalborg:
        +materialized: table
        +schema: AALBORG
      esbjerg:
        +materialized: table
        +schema: ESBJERG
      analytics:
        +materialized: table
        +schema: ANALYTICS
