kombit:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      role: SYSADMIN
      warehouse: COMPUTE_WH
      database: KOMBIT_C_DBT
      schema: RAW
      threads: 4
