WITH benefits AS (
    SELECT * FROM {{ ref('stg_ydelser') }}
    WHERE KOMMUNE_ID = 'COPENHAGEN'
),

citizens AS (
    SELECT CITIZEN_ID, FULDE_NAVN_COMPUTED, ALDERSGRUPPE FROM {{ ref('stg_citizens') }}
    WHERE KOMMUNE_ID = 'COPENHAGEN'
)

SELECT
    y.YDELSE_ID,
    y.YDELSESNUMMER,
    y.KOMMUNE_ID,
    y.CITIZEN_ID,
    c.FULDE_NAVN_COMPUTED AS BORGER_NAVN,
    c.ALDERSGRUPPE AS BORGER_ALDERSGRUPPE,
    y.YDELSE_TYPE_KODE,
    y.YDELSE_BESKRIVELSE,
    y.BELOEB_VALIDERET AS BELOEB,
    y.BELOEB_NIVEAU,
    y.AARLIGT_BELOEB_EST,
    y.UDBETALING_DATO,
    y.PERIODE_START,
    y.PERIODE_SLUT,
    y.ER_AKTIV,
    y.YDELSE_VARIGHED_DAGE,
    
    CURRENT_TIMESTAMP() AS SIDST_OPDATERET

FROM benefits y
LEFT JOIN citizens c ON y.CITIZEN_ID = c.CITIZEN_ID
