WITH cases AS (
    SELECT * FROM {{ ref('stg_sager') }}
    WHERE KOMMUNE_ID = 'COPENHAGEN'
),

citizens AS (
    SELECT CITIZEN_ID, FULDE_NAVN_COMPUTED, ALDERSGRUPPE FROM {{ ref('stg_citizens') }}
    WHERE KOMMUNE_ID = 'COPENHAGEN'
)

SELECT
    s.SAG_ID,
    s.SAGSNUMMER,
    s.KOMMUNE_ID,
    s.CITIZEN_ID,
    c.FULDE_NAVN_COMPUTED AS BORGER_NAVN,
    c.ALDERSGRUPPE AS BORGER_ALDERSGRUPPE,
    s.SAG_TYPE_KODE,
    s.SAG_TYPE_BESKRIVELSE,
    s.STATUS_KODE,
    s.STATUS_BESKRIVELSE,
    s.ER_AKTIV,
    s.OPRETTET_DATO,
    s.AFSLUTTET_DATO,
    s.SAG_VARIGHED_DAGE,
    s.VARIGHED_KATEGORI,
    s.SAGSBEHANDLER,
    
    CASE 
        WHEN s.SAG_VARIGHED_DAGE <= 30 THEN 'OVERHOLDT'
        WHEN s.SAG_VARIGHED_DAGE <= 45 THEN 'ADVARSEL'
        ELSE 'OVERSKREDET'
    END AS SLA_STATUS,
    
    CURRENT_TIMESTAMP() AS SIDST_OPDATERET

FROM cases s
LEFT JOIN citizens c ON s.CITIZEN_ID = c.CITIZEN_ID
