WITH properties AS (
    SELECT * FROM {{ ref('stg_ejendomme') }}
    WHERE KOMMUNE_ID = 'COPENHAGEN'
)

SELECT
    p.EJENDOM_ID,
    p.MATRIKELNUMMER,
    p.KOMMUNE_ID,
    p.EJER_CPR,
    p.FULD_ADRESSE,
    p.EJENDOMSTYPE_KODE,
    p.EJENDOMSTYPE_BESKRIVELSE,
    p.VURDERING_VALIDERET AS VURDERING,
    p.VAERDI_NIVEAU,
    p.AREAL_M2,
    p.STOERRELSE_KATEGORI,
    p.PRIS_PR_M2,
    
    CURRENT_TIMESTAMP() AS SIDST_OPDATERET

FROM properties p
