WITH source AS (
    SELECT * FROM {{ source('raw', 'sager') }}
    WHERE KOMMUNE_ID = 'ODENSE'
)
SELECT
    SAG_ID,
    SAGSNUMMER,
    CITIZEN_ID,
    KOMMUNE_ID,
    TRIM(UPPER(SAG_TYPE)) AS SAG_TYPE,
    TRIM(UPPER(SAG_STATUS)) AS STATUS,
    CASE WHEN TRIM(UPPER(SAG_STATUS)) IN ('AABEN', 'AFVENTER') THEN TRUE ELSE FALSE END AS ER_AKTIV,
    OPRETTET_DATO,
    AFSLUTTET_DATO,
    DATEDIFF(DAY, OPRETTET_DATO, COALESCE(AFSLUTTET_DATO, CURRENT_DATE())) AS VARIGHED_DAGE,
    SAGSBEHANDLER,
    CURRENT_TIMESTAMP() AS OPDATERET
FROM source
