WITH source AS (
    SELECT * FROM {{ source('raw', 'ydelser') }}
    WHERE KOMMUNE_ID = 'ODENSE'
)
SELECT
    YDELSE_ID,
    YDELSESNUMMER,
    CITIZEN_ID,
    KOMMUNE_ID,
    TRIM(UPPER(YDELSE_TYPE)) AS YDELSE_TYPE,
    BELOEB,
    BELOEB * 12 AS AARLIGT_BELOEB,
    CASE 
        WHEN BELOEB >= 20000 THEN 'HOEJ'
        WHEN BELOEB >= 10000 THEN 'MELLEM'
        ELSE 'LAV'
    END AS BELOEB_NIVEAU,
    PERIODE_START,
    PERIODE_SLUT,
    CASE WHEN PERIODE_SLUT IS NULL OR PERIODE_SLUT >= CURRENT_DATE() THEN TRUE ELSE FALSE END AS ER_AKTIV,
    CURRENT_TIMESTAMP() AS OPDATERET
FROM source
