name: 'kombit_esbjerg'
version: '1.0.0'
config-version: 2
profile: 'kombit'

model-paths: ["models"]
macro-paths: ["macros"]

models:
  kombit_esbjerg:
    staging:
      +materialized: view
      +schema: STAGING
    marts:
      +materialized: table
      +schema: ESBJERG
