WITH citizens AS (
    SELECT * FROM {{ ref('stg_citizens') }}
),
cases AS (
    SELECT CITIZEN_ID, COUNT(*) AS SAGER, SUM(CASE WHEN ER_AKTIV THEN 1 ELSE 0 END) AS AKTIVE_SAGER
    FROM {{ ref('stg_sager') }}
    GROUP BY CITIZEN_ID
),
benefits AS (
    SELECT CITIZEN_ID, COUNT(*) AS YDELSER, SUM(CASE WHEN ER_AKTIV THEN AARLIGT_BELOEB ELSE 0 END) AS AARLIG_YDELSE
    FROM {{ ref('stg_ydelser') }}
    GROUP BY CITIZEN_ID
)
SELECT
    c.CITIZEN_ID,
    c.KOMMUNE_ID,
    c.FULDE_NAVN,
    c.CPR_NUMMER,
    c.ADRESSE,
    c.POSTNUMMER,
    c.BY_NAVN,
    c.TELEFON,
    c.EMAIL,
    c.FOEDSELSDATO,
    c.ALDER,
    c.ALDERSGRUPPE,
    c.KOEN,
    COALESCE(s.SAGER, 0) AS TOTAL_SAGER,
    COALESCE(s.AKTIVE_SAGER, 0) AS AKTIVE_SAGER,
    COALESCE(b.YDELSER, 0) AS TOTAL_YDELSER,
    COALESCE(b.AARLIG_YDELSE, 0) AS AARLIG_YDELSE,
    CASE 
        WHEN COALESCE(s.AKTIVE_SAGER, 0) > 2 OR COALESCE(b.AARLIG_YDELSE, 0) > 50000 THEN 'HOEJ'
        WHEN COALESCE(s.AKTIVE_SAGER, 0) > 0 OR COALESCE(b.YDELSER, 0) > 0 THEN 'MELLEM'
        ELSE 'LAV'
    END AS ENGAGEMENT,
    CURRENT_TIMESTAMP() AS OPDATERET
FROM citizens c
LEFT JOIN cases s ON c.CITIZEN_ID = s.CITIZEN_ID
LEFT JOIN benefits b ON c.CITIZEN_ID = b.CITIZEN_ID
