WITH benefits AS (
    SELECT * FROM {{ ref('stg_ydelser') }}
)

SELECT
    KOMMUNE_ID,
    YDELSE_TYPE_KODE,
    YDELSE_BESKRIVELSE,
    
    COUNT(*) AS TOTAL_YDELSER,
    SUM(CASE WHEN ER_AKTIV THEN 1 ELSE 0 END) AS AKTIVE_YDELSER,
    
    SUM(BELOEB_VALIDERET) AS TOTAL_UDBETALT,
    SUM(AARLIGT_BELOEB_EST) AS TOTAL_AARLIG_FORPLIGTELSE,
    AVG(BELOEB_VALIDERET) AS GNS_YDELSE_BELOEB,
    
    SUM(CASE WHEN BELOEB_NIVEAU = 'HOEJ_VAERDI' THEN 1 ELSE 0 END) AS HOEJ_VAERDI_ANTAL,
    SUM(CASE WHEN BELOEB_NIVEAU = 'MELLEM_VAERDI' THEN 1 ELSE 0 END) AS MELLEM_VAERDI_ANTAL,
    SUM(CASE WHEN BELOEB_NIVEAU = 'LAV_VAERDI' THEN 1 ELSE 0 END) AS LAV_VAERDI_ANTAL,
    
    AVG(YDELSE_VARIGHED_DAGE) AS GNS_YDELSE_VARIGHED_DAGE,
    
    CURRENT_TIMESTAMP() AS GENERERET_TIDSPUNKT

FROM benefits
GROUP BY KOMMUNE_ID, YDELSE_TYPE_KODE, YDELSE_BESKRIVELSE
