WITH cases AS (
    SELECT * FROM {{ ref('stg_sager') }}
)

SELECT
    KOMMUNE_ID,
    SAG_TYPE_KODE,
    SAG_TYPE_BESKRIVELSE,
    
    COUNT(*) AS TOTAL_SAGER,
    SUM(CASE WHEN ER_AKTIV THEN 1 ELSE 0 END) AS AKTIVE_SAGER,
    SUM(CASE WHEN NOT ER_AKTIV THEN 1 ELSE 0 END) AS AFSLUTTEDE_SAGER,
    
    AVG(SAG_VARIGHED_DAGE) AS GNS_VARIGHED_DAGE,
    MIN(SAG_VARIGHED_DAGE) AS MIN_VARIGHED_DAGE,
    MAX(SAG_VARIGHED_DAGE) AS MAX_VARIGHED_DAGE,
    
    SUM(CASE WHEN SAG_VARIGHED_DAGE <= 30 THEN 1 ELSE 0 END) AS SLA_OVERHOLDT,
    ROUND(100.0 * SUM(CASE WHEN SAG_VARIGHED_DAGE <= 30 THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 2) AS SLA_OVERHOLDELSE_PCT,
    
    CURRENT_TIMESTAMP() AS GENERERET_TIDSPUNKT

FROM cases
GROUP BY KOMMUNE_ID, SAG_TYPE_KODE, SAG_TYPE_BESKRIVELSE
