WITH all_citizens AS (
    SELECT * FROM {{ ref('stg_citizens') }}
),

all_cases AS (
    SELECT * FROM {{ ref('stg_sager') }}
),

all_benefits AS (
    SELECT * FROM {{ ref('stg_ydelser') }}
),

all_properties AS (
    SELECT * FROM {{ ref('stg_ejendomme') }}
)

SELECT
    c.KOMMUNE_ID,
    
    COUNT(DISTINCT c.CITIZEN_ID) AS TOTAL_BORGERE,
    AVG(c.ALDER_AAR) AS GNS_BORGER_ALDER,
    SUM(CASE WHEN c.ALDERSGRUPPE = 'BARN' THEN 1 ELSE 0 END) AS ANTAL_BOERN,
    SUM(CASE WHEN c.ALDERSGRUPPE = 'AELDRE' THEN 1 ELSE 0 END) AS ANTAL_AELDRE,
    
    COUNT(DISTINCT s.SAG_ID) AS TOTAL_SAGER,
    SUM(CASE WHEN s.ER_AKTIV THEN 1 ELSE 0 END) AS AKTIVE_SAGER,
    AVG(s.SAG_VARIGHED_DAGE) AS GNS_SAG_VARIGHED_DAGE,
    
    COUNT(DISTINCT y.YDELSE_ID) AS TOTAL_YDELSER,
    SUM(CASE WHEN y.ER_AKTIV THEN 1 ELSE 0 END) AS AKTIVE_YDELSER,
    SUM(y.AARLIGT_BELOEB_EST) AS TOTAL_AARLIG_YDELSE_UDGIFT,
    AVG(y.AARLIGT_BELOEB_EST) AS GNS_AARLIG_YDELSE_PR_PERSON,
    
    COUNT(DISTINCT p.EJENDOM_ID) AS TOTAL_EJENDOMME,
    AVG(p.VURDERING_VALIDERET) AS GNS_EJENDOMSVAERDI,
    SUM(p.VURDERING_VALIDERET) AS TOTAL_EJENDOMSVAERDI,
    AVG(p.AREAL_M2) AS GNS_EJENDOMS_AREAL,
    
    CURRENT_TIMESTAMP() AS GENERERET_TIDSPUNKT

FROM all_citizens c
LEFT JOIN all_cases s ON c.CITIZEN_ID = s.CITIZEN_ID AND c.KOMMUNE_ID = s.KOMMUNE_ID
LEFT JOIN all_benefits y ON c.CITIZEN_ID = y.CITIZEN_ID AND c.KOMMUNE_ID = y.KOMMUNE_ID
LEFT JOIN all_properties p ON c.KOMMUNE_ID = p.KOMMUNE_ID
GROUP BY c.KOMMUNE_ID
