{% macro create_citizen_mart(kommune_id) %}

WITH citizens AS (
    SELECT * FROM {{ ref('stg_citizens') }}
    WHERE KOMMUNE_ID = '{{ kommune_id }}'
),

cases AS (
    SELECT * FROM {{ ref('stg_sager') }}
    WHERE KOMMUNE_ID = '{{ kommune_id }}'
),

benefits AS (
    SELECT * FROM {{ ref('stg_ydelser') }}
    WHERE KOMMUNE_ID = '{{ kommune_id }}'
),

citizen_cases AS (
    SELECT
        c.CITIZEN_ID,
        COUNT(DISTINCT s.SAG_ID) AS TOTAL_SAGER,
        SUM(CASE WHEN s.ER_AKTIV THEN 1 ELSE 0 END) AS AKTIVE_SAGER,
        AVG(s.SAG_VARIGHED_DAGE) AS GNS_SAG_VARIGHED
    FROM citizens c
    LEFT JOIN cases s ON c.CITIZEN_ID = s.CITIZEN_ID
    GROUP BY c.CITIZEN_ID
),

citizen_benefits AS (
    SELECT
        c.CITIZEN_ID,
        COUNT(DISTINCT y.YDELSE_ID) AS TOTAL_YDELSER,
        SUM(CASE WHEN y.ER_AKTIV THEN 1 ELSE 0 END) AS AKTIVE_YDELSER,
        SUM(CASE WHEN y.ER_AKTIV THEN y.AARLIGT_BELOEB_EST ELSE 0 END) AS TOTAL_AARLIGE_YDELSER
    FROM citizens c
    LEFT JOIN benefits y ON c.CITIZEN_ID = y.CITIZEN_ID
    GROUP BY c.CITIZEN_ID
)

SELECT
    c.CITIZEN_ID,
    c.KOMMUNE_ID,
    c.FULDE_NAVN_COMPUTED AS FULDE_NAVN,
    c.CPR_NUMMER,
    c.ADRESSE_STANDARDIZED AS ADRESSE,
    c.POSTNUMMER,
    c.BY_NAVN_STANDARDIZED AS BY_NAVN,
    c.TELEFON_NORMALIZED AS TELEFON,
    c.EMAIL_NORMALIZED AS EMAIL,
    c.FOEDSELSDATO,
    c.ALDER_AAR,
    c.ALDERSGRUPPE,
    c.KOEN,
    c.DAGE_SIDEN_OPRETTELSE,
    COALESCE(cs.TOTAL_SAGER, 0) AS TOTAL_SAGER,
    COALESCE(cs.AKTIVE_SAGER, 0) AS AKTIVE_SAGER,
    COALESCE(cs.GNS_SAG_VARIGHED, 0) AS GNS_SAG_VARIGHED_DAGE,
    COALESCE(cb.TOTAL_YDELSER, 0) AS TOTAL_YDELSER,
    COALESCE(cb.AKTIVE_YDELSER, 0) AS AKTIVE_YDELSER,
    COALESCE(cb.TOTAL_AARLIGE_YDELSER, 0) AS AARLIGT_YDELSE_BELOEB,
    CASE 
        WHEN COALESCE(cs.AKTIVE_SAGER, 0) > 2 OR COALESCE(cb.TOTAL_AARLIGE_YDELSER, 0) > 50000 THEN 'HOEJ'
        WHEN COALESCE(cs.AKTIVE_SAGER, 0) > 0 OR COALESCE(cb.AKTIVE_YDELSER, 0) > 0 THEN 'MELLEM'
        ELSE 'LAV'
    END AS ENGAGEMENT_NIVEAU,
    CURRENT_TIMESTAMP() AS SIDST_OPDATERET
FROM citizens c
LEFT JOIN citizen_cases cs ON c.CITIZEN_ID = cs.CITIZEN_ID
LEFT JOIN citizen_benefits cb ON c.CITIZEN_ID = cb.CITIZEN_ID

{% endmacro %}
