WITH source AS (
    SELECT * FROM {{ source('raw', 'citizens') }}
    WHERE KOMMUNE_ID = 'AALBORG'
)
SELECT
    CITIZEN_ID,
    KOMMUNE_ID,
    TRIM(UPPER(FORNAVN)) || ' ' || TRIM(UPPER(EFTERNAVN)) AS FULDE_NAVN,
    CPR_NUMMER,
    TRIM(INITCAP(ADRESSE)) AS ADRESSE,
    POSTNUMMER,
    TRIM(INITCAP(BY_NAVN)) AS BY_NAVN,
    REGEXP_REPLACE(TELEFON, '[^0-9+]', '') AS TELEFON,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    FOEDSELSDATO,
    DATEDIFF(YEAR, FOEDSELSDATO, CURRENT_DATE()) AS ALDER,
    CASE 
        WHEN DATEDIFF(YEAR, FOEDSELSDATO, CURRENT_DATE()) < 18 THEN 'BARN'
        WHEN DATEDIFF(YEAR, FOEDSELSDATO, CURRENT_DATE()) < 30 THEN 'UNG_VOKSEN'
        WHEN DATEDIFF(YEAR, FOEDSELSDATO, CURRENT_DATE()) < 50 THEN 'VOKSEN'
        WHEN DATEDIFF(YEAR, FOEDSELSDATO, CURRENT_DATE()) < 67 THEN 'SENIOR'
        ELSE 'AELDRE'
    END AS ALDERSGRUPPE,
    KOEN,
    CURRENT_TIMESTAMP() AS OPDATERET
FROM source
