WITH source AS (
    SELECT * FROM {{ source('raw', 'ejendomme') }}
    WHERE KOMMUNE_ID = 'AALBORG'
)
SELECT
    EJENDOM_ID,
    MATRIKELNUMMER,
    EJER_CPR,
    KOMMUNE_ID,
    TRIM(INITCAP(ADRESSE)) || ', ' || POSTNUMMER || ' ' || TRIM(INITCAP(BY_NAVN)) AS FULD_ADRESSE,
    TRIM(UPPER(EJENDOMSTYPE)) AS EJENDOMSTYPE,
    VURDERING,
    CASE 
        WHEN VURDERING >= 5000000 THEN 'LUKSUS'
        WHEN VURDERING >= 2500000 THEN 'HOEJ'
        WHEN VURDERING >= 1500000 THEN 'MELLEM'
        ELSE 'STANDARD'
    END AS VAERDI_NIVEAU,
    AREAL_M2,
    CASE WHEN AREAL_M2 > 0 THEN ROUND(VURDERING / AREAL_M2, 2) ELSE 0 END AS PRIS_PR_M2,
    CURRENT_TIMESTAMP() AS OPDATERET
FROM source
