-- ============================================================================
-- KOMBIT Demo: Pattern B - Top-Down Distribution
-- 1 Central DB → Municipality Schemas via Dynamic Tables
-- ============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================================
-- STEP 1: Create Central Database with All Schemas
-- ============================================================================

CREATE OR REPLACE DATABASE KOMBIT_B_DISTRIBUTED COMMENT = 'Central DB with municipality distribution';

-- Source schemas
CREATE SCHEMA IF NOT EXISTS KOMBIT_B_DISTRIBUTED.RAW;
CREATE SCHEMA IF NOT EXISTS KOMBIT_B_DISTRIBUTED.STAGING;

-- Municipality output schemas
CREATE SCHEMA IF NOT EXISTS KOMBIT_B_DISTRIBUTED.COPENHAGEN;
CREATE SCHEMA IF NOT EXISTS KOMBIT_B_DISTRIBUTED.AARHUS;
CREATE SCHEMA IF NOT EXISTS KOMBIT_B_DISTRIBUTED.ODENSE;
CREATE SCHEMA IF NOT EXISTS KOMBIT_B_DISTRIBUTED.AALBORG;
CREATE SCHEMA IF NOT EXISTS KOMBIT_B_DISTRIBUTED.ESBJERG;

-- ============================================================================
-- STEP 2: Create Central Source Tables
-- ============================================================================

CREATE OR REPLACE TABLE KOMBIT_B_DISTRIBUTED.RAW.CITIZENS (
    CITIZEN_ID VARCHAR(36) DEFAULT UUID_STRING(),
    CPR_NUMMER VARCHAR(11),
    FORNAVN VARCHAR(100),
    EFTERNAVN VARCHAR(100),
    FULDE_NAVN VARCHAR(200),
    FOEDSELSDATO DATE,
    KOEN VARCHAR(10),
    ADRESSE VARCHAR(200),
    POSTNUMMER VARCHAR(4),
    BY_NAVN VARCHAR(100),
    KOMMUNE_ID VARCHAR(50),  -- Distribution key
    TELEFON VARCHAR(20),
    EMAIL VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- (Similar tables for SAGER, YDELSER, EJENDOMME)

-- ============================================================================
-- STEP 3: Dynamic Tables for Distribution (filter by KOMMUNE_ID)
-- ============================================================================

-- Copenhagen
CREATE OR REPLACE DYNAMIC TABLE KOMBIT_B_DISTRIBUTED.COPENHAGEN.CITIZENS
    TARGET_LAG = '1 hour'
    WAREHOUSE = KOMBIT_COPENHAGEN_WH
AS
SELECT * FROM KOMBIT_B_DISTRIBUTED.RAW.CITIZENS WHERE KOMMUNE_ID = 'COPENHAGEN';

-- Aarhus
CREATE OR REPLACE DYNAMIC TABLE KOMBIT_B_DISTRIBUTED.AARHUS.CITIZENS
    TARGET_LAG = '1 hour'
    WAREHOUSE = KOMBIT_AARHUS_WH
AS
SELECT * FROM KOMBIT_B_DISTRIBUTED.RAW.CITIZENS WHERE KOMMUNE_ID = 'AARHUS';

-- Odense
CREATE OR REPLACE DYNAMIC TABLE KOMBIT_B_DISTRIBUTED.ODENSE.CITIZENS
    TARGET_LAG = '1 hour'
    WAREHOUSE = KOMBIT_ODENSE_WH
AS
SELECT * FROM KOMBIT_B_DISTRIBUTED.RAW.CITIZENS WHERE KOMMUNE_ID = 'ODENSE';

-- Aalborg
CREATE OR REPLACE DYNAMIC TABLE KOMBIT_B_DISTRIBUTED.AALBORG.CITIZENS
    TARGET_LAG = '1 hour'
    WAREHOUSE = KOMBIT_AALBORG_WH
AS
SELECT * FROM KOMBIT_B_DISTRIBUTED.RAW.CITIZENS WHERE KOMMUNE_ID = 'AALBORG';

-- Esbjerg
CREATE OR REPLACE DYNAMIC TABLE KOMBIT_B_DISTRIBUTED.ESBJERG.CITIZENS
    TARGET_LAG = '1 hour'
    WAREHOUSE = KOMBIT_ESBJERG_WH
AS
SELECT * FROM KOMBIT_B_DISTRIBUTED.RAW.CITIZENS WHERE KOMMUNE_ID = 'ESBJERG';

-- (Similar Dynamic Tables for SAGER, YDELSER, EJENDOMME)

-- ============================================================================
-- STEP 4: Apply Governance
-- ============================================================================

-- Apply masking policies to source table
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.CITIZENS 
    MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.CITIZENS 
    MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;

-- Apply row access policy to source (inherited by Dynamic Tables)
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.CITIZENS 
    ADD ROW ACCESS POLICY KOMBIT_GOVERNANCE.POLICIES.KOMMUNE_DATA_ACCESS ON (KOMMUNE_ID);

-- ============================================================================
-- STEP 5: Grant Access to Municipality Roles
-- ============================================================================

USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE KOMBIT_B_DISTRIBUTED TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT USAGE ON SCHEMA KOMBIT_B_DISTRIBUTED.COPENHAGEN TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA KOMBIT_B_DISTRIBUTED.COPENHAGEN TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA KOMBIT_B_DISTRIBUTED.COPENHAGEN TO ROLE KOMBIT_COPENHAGEN_ROLE;

-- (Repeat for other municipalities)
