SELECT
    KOMMUNE_ID,
    COUNT(DISTINCT CITIZEN_ID) AS TOTAL_BORGERE,
    AVG(ALDER) AS GNS_ALDER,
    SUM(CASE WHEN ALDERSGRUPPE = 'BARN' THEN 1 ELSE 0 END) AS BOERN,
    SUM(CASE WHEN ALDERSGRUPPE = 'AELDRE' THEN 1 ELSE 0 END) AS AELDRE,
    SUM(TOTAL_SAGER) AS TOTAL_SAGER,
    SUM(AKTIVE_SAGER) AS AKTIVE_SAGER,
    SUM(TOTAL_YDELSER) AS TOTAL_YDELSER,
    SUM(AARLIG_YDELSE) AS SAMLET_AARLIG_YDELSE,
    AVG(AARLIG_YDELSE) AS GNS_YDELSE_PR_BORGER,
    CURRENT_TIMESTAMP() AS GENERERET
FROM {{ ref('mart_citizens') }}
GROUP BY KOMMUNE_ID
