-- ============================================================================
-- KOMBIT Demo: Dynamic Data Masking Policies
-- Role-based PII protection for Danish government data
-- ============================================================================
-- 
-- IMPORTANT DESIGN NOTES:
-- 1. Use CURRENT_ROLE() not IS_ROLE_IN_SESSION() to avoid role hierarchy bypass
-- 2. For Pattern A (Dynamic Tables): Apply masking to DTs only, NOT source tables
--    - DTs evaluate masking at query time when applied to the DT itself
--    - If applied to source tables, DT refresh would store masked data
-- 3. For Patterns B & C: Apply masking directly to tables/views
--
-- PII COVERAGE:
-- - CPR_MASK: Danish personal ID (CPR-nummer) - format DDMMYY-XXXX
-- - NAME_MASK: First names, last names, full names
-- - ADDRESS_MASK: Street addresses with house numbers
-- - EMAIL_MASK: Email addresses
-- - PHONE_MASK: Danish phone numbers
-- ============================================================================

USE ROLE SYSADMIN;
CREATE SCHEMA IF NOT EXISTS KOMBIT_GOVERNANCE.POLICIES;

-- ============================================================================
-- MASKING POLICY DEFINITIONS
-- ============================================================================

-- CPR Masking (Danish Personal ID - DDMMYY-XXXX format)
-- Admin/Steward: Full access | Municipality roles: Full access | Analyst: Partial | Others: Full mask
CREATE OR REPLACE MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() IN ('KOMBIT_COPENHAGEN_ROLE', 'KOMBIT_AARHUS_ROLE', 'KOMBIT_ODENSE_ROLE', 'KOMBIT_AALBORG_ROLE', 'KOMBIT_ESBJERG_ROLE') THEN val
        WHEN CURRENT_ROLE() = 'KOMBIT_ANALYST' THEN CONCAT('XXXXXX-', RIGHT(val, 4))
        ELSE '******-****'
    END;

-- Name Masking (first initial only for analyst)
CREATE OR REPLACE MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() IN ('KOMBIT_COPENHAGEN_ROLE', 'KOMBIT_AARHUS_ROLE', 'KOMBIT_ODENSE_ROLE', 'KOMBIT_AALBORG_ROLE', 'KOMBIT_ESBJERG_ROLE') THEN val
        WHEN CURRENT_ROLE() = 'KOMBIT_ANALYST' THEN CONCAT(LEFT(val, 1), '****')
        ELSE '****'
    END;

-- Address Masking (hide house numbers for analyst)
CREATE OR REPLACE MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() IN ('KOMBIT_COPENHAGEN_ROLE', 'KOMBIT_AARHUS_ROLE', 'KOMBIT_ODENSE_ROLE', 'KOMBIT_AALBORG_ROLE', 'KOMBIT_ESBJERG_ROLE') THEN val
        WHEN CURRENT_ROLE() = 'KOMBIT_ANALYST' THEN REGEXP_REPLACE(val, '[0-9]+', '***')
        ELSE '*** MASKED ***'
    END;

-- Phone Masking (show last 2 digits for analyst)
CREATE OR REPLACE MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() IN ('KOMBIT_COPENHAGEN_ROLE', 'KOMBIT_AARHUS_ROLE', 'KOMBIT_ODENSE_ROLE', 'KOMBIT_AALBORG_ROLE', 'KOMBIT_ESBJERG_ROLE') THEN val
        WHEN CURRENT_ROLE() = 'KOMBIT_ANALYST' THEN CONCAT('+45 XX XX ', RIGHT(val, 2))
        ELSE '+45 XX XX XX'
    END;

-- Email Masking (show domain + first 2 chars for analyst)
CREATE OR REPLACE MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() IN ('KOMBIT_COPENHAGEN_ROLE', 'KOMBIT_AARHUS_ROLE', 'KOMBIT_ODENSE_ROLE', 'KOMBIT_AALBORG_ROLE', 'KOMBIT_ESBJERG_ROLE') THEN val
        WHEN CURRENT_ROLE() = 'KOMBIT_ANALYST' THEN CONCAT(LEFT(SPLIT_PART(val, '@', 1), 2), '***@', SPLIT_PART(val, '@', 2))
        ELSE '***@***.dk'
    END;

-- ============================================================================
-- PATTERN A: AGGREGATED DYNAMIC TABLES (Apply to DTs only!)
-- ============================================================================

-- DT_ALL_CITIZENS - Full PII coverage
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS MODIFY COLUMN EFTERNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS MODIFY COLUMN FULDE_NAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS MODIFY COLUMN EMAIL SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK;
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS MODIFY COLUMN TELEFON SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK;

-- DT_ALL_SAGER
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_SAGER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;

-- DT_ALL_YDELSER  
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_YDELSER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;

-- DT_ALL_EJENDOMME
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_EJENDOMME MODIFY COLUMN EJER_CPR SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_EJENDOMME MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;

-- ============================================================================
-- PATTERN B: DISTRIBUTED (Central RAW tables with RLS)
-- ============================================================================

-- CITIZENS - Full PII coverage
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.CITIZENS MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.CITIZENS MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.CITIZENS MODIFY COLUMN EFTERNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.CITIZENS MODIFY COLUMN FULDE_NAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.CITIZENS MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.CITIZENS MODIFY COLUMN EMAIL SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK;
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.CITIZENS MODIFY COLUMN TELEFON SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK;

-- SAGER, YDELSER, EJENDOMME
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.SAGER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.YDELSER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.EJENDOMME MODIFY COLUMN EJER_CPR SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_B_DISTRIBUTED.RAW.EJENDOMME MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;

-- ============================================================================
-- PATTERN C: DBT (RAW → STAGING → MARTS per municipality)
-- ============================================================================

-- RAW Layer
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS MODIFY COLUMN EFTERNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS MODIFY COLUMN FULDE_NAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS MODIFY COLUMN EMAIL SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS MODIFY COLUMN TELEFON SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.SAGER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.YDELSER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.EJENDOMME MODIFY COLUMN EJER_CPR SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.EJENDOMME MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;

-- STAGING Layer (Views)
ALTER VIEW KOMBIT_C_DBT.STAGING.STG_CITIZENS MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER VIEW KOMBIT_C_DBT.STAGING.STG_CITIZENS MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER VIEW KOMBIT_C_DBT.STAGING.STG_CITIZENS MODIFY COLUMN EFTERNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER VIEW KOMBIT_C_DBT.STAGING.STG_CITIZENS MODIFY COLUMN FULDE_NAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER VIEW KOMBIT_C_DBT.STAGING.STG_CITIZENS MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;
ALTER VIEW KOMBIT_C_DBT.STAGING.STG_CITIZENS MODIFY COLUMN EMAIL SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK;
ALTER VIEW KOMBIT_C_DBT.STAGING.STG_CITIZENS MODIFY COLUMN TELEFON SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK;
ALTER VIEW KOMBIT_C_DBT.STAGING.STG_SAGER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER VIEW KOMBIT_C_DBT.STAGING.STG_YDELSER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER VIEW KOMBIT_C_DBT.STAGING.STG_EJENDOMME MODIFY COLUMN EJER_CPR SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER VIEW KOMBIT_C_DBT.STAGING.STG_EJENDOMME MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;

-- MARTS Layer - Copenhagen
ALTER TABLE KOMBIT_C_DBT.COPENHAGEN.MRT_CITIZENS MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.COPENHAGEN.MRT_CITIZENS MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.COPENHAGEN.MRT_CITIZENS MODIFY COLUMN EFTERNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.COPENHAGEN.MRT_CITIZENS MODIFY COLUMN FULDE_NAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.COPENHAGEN.MRT_CITIZENS MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;
ALTER TABLE KOMBIT_C_DBT.COPENHAGEN.MRT_CITIZENS MODIFY COLUMN EMAIL SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK;
ALTER TABLE KOMBIT_C_DBT.COPENHAGEN.MRT_CITIZENS MODIFY COLUMN TELEFON SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK;
ALTER TABLE KOMBIT_C_DBT.COPENHAGEN.MRT_SAGER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.COPENHAGEN.MRT_YDELSER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.COPENHAGEN.MRT_EJENDOMME MODIFY COLUMN EJER_CPR SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.COPENHAGEN.MRT_EJENDOMME MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;

-- MARTS Layer - Aarhus
ALTER TABLE KOMBIT_C_DBT.AARHUS.MRT_CITIZENS MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.AARHUS.MRT_CITIZENS MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.AARHUS.MRT_CITIZENS MODIFY COLUMN EFTERNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.AARHUS.MRT_CITIZENS MODIFY COLUMN FULDE_NAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.AARHUS.MRT_CITIZENS MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;
ALTER TABLE KOMBIT_C_DBT.AARHUS.MRT_CITIZENS MODIFY COLUMN EMAIL SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK;
ALTER TABLE KOMBIT_C_DBT.AARHUS.MRT_CITIZENS MODIFY COLUMN TELEFON SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK;
ALTER TABLE KOMBIT_C_DBT.AARHUS.MRT_SAGER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.AARHUS.MRT_YDELSER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.AARHUS.MRT_EJENDOMME MODIFY COLUMN EJER_CPR SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.AARHUS.MRT_EJENDOMME MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;

-- MARTS Layer - Odense
ALTER TABLE KOMBIT_C_DBT.ODENSE.MRT_CITIZENS MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.ODENSE.MRT_CITIZENS MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.ODENSE.MRT_CITIZENS MODIFY COLUMN EFTERNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.ODENSE.MRT_CITIZENS MODIFY COLUMN FULDE_NAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.ODENSE.MRT_CITIZENS MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;
ALTER TABLE KOMBIT_C_DBT.ODENSE.MRT_CITIZENS MODIFY COLUMN EMAIL SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK;
ALTER TABLE KOMBIT_C_DBT.ODENSE.MRT_CITIZENS MODIFY COLUMN TELEFON SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK;
ALTER TABLE KOMBIT_C_DBT.ODENSE.MRT_SAGER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.ODENSE.MRT_YDELSER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.ODENSE.MRT_EJENDOMME MODIFY COLUMN EJER_CPR SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.ODENSE.MRT_EJENDOMME MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;

-- MARTS Layer - Aalborg
ALTER TABLE KOMBIT_C_DBT.AALBORG.MRT_CITIZENS MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.AALBORG.MRT_CITIZENS MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.AALBORG.MRT_CITIZENS MODIFY COLUMN EFTERNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.AALBORG.MRT_CITIZENS MODIFY COLUMN FULDE_NAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.AALBORG.MRT_CITIZENS MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;
ALTER TABLE KOMBIT_C_DBT.AALBORG.MRT_CITIZENS MODIFY COLUMN EMAIL SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK;
ALTER TABLE KOMBIT_C_DBT.AALBORG.MRT_CITIZENS MODIFY COLUMN TELEFON SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK;
ALTER TABLE KOMBIT_C_DBT.AALBORG.MRT_SAGER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.AALBORG.MRT_YDELSER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.AALBORG.MRT_EJENDOMME MODIFY COLUMN EJER_CPR SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.AALBORG.MRT_EJENDOMME MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;

-- MARTS Layer - Esbjerg
ALTER TABLE KOMBIT_C_DBT.ESBJERG.MRT_CITIZENS MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.ESBJERG.MRT_CITIZENS MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.ESBJERG.MRT_CITIZENS MODIFY COLUMN EFTERNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.ESBJERG.MRT_CITIZENS MODIFY COLUMN FULDE_NAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.ESBJERG.MRT_CITIZENS MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;
ALTER TABLE KOMBIT_C_DBT.ESBJERG.MRT_CITIZENS MODIFY COLUMN EMAIL SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK;
ALTER TABLE KOMBIT_C_DBT.ESBJERG.MRT_CITIZENS MODIFY COLUMN TELEFON SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK;
ALTER TABLE KOMBIT_C_DBT.ESBJERG.MRT_SAGER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.ESBJERG.MRT_YDELSER MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.ESBJERG.MRT_EJENDOMME MODIFY COLUMN EJER_CPR SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.ESBJERG.MRT_EJENDOMME MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Count policy applications
-- SELECT POLICY_NAME, COUNT(*) FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => 'KOMBIT_GOVERNANCE.POLICIES.CPR_MASK')) GROUP BY 1;

-- Test as KOMBIT_ANALYST (should see masked data):
-- USE ROLE KOMBIT_ANALYST;
-- SELECT CPR_NUMMER, FORNAVN, EMAIL FROM KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS LIMIT 3;
-- Expected: XXXXXX-1234, W****, wi***@email.dk

-- Test as KOMBIT_ADMIN (should see full data):
-- USE ROLE KOMBIT_ADMIN;
-- SELECT CPR_NUMMER, FORNAVN, EMAIL FROM KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS LIMIT 3;
-- Expected: 010185-1234, William, william.test@email.dk
