-- ============================================================================
-- KOMBIT Demo: Masking Policies
-- Role-based dynamic data masking for PII protection
-- ============================================================================

USE ROLE SYSADMIN;

CREATE SCHEMA IF NOT EXISTS KOMBIT_GOVERNANCE.POLICIES;

-- CPR Masking (Danish Personal ID)
CREATE OR REPLACE MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() LIKE 'KOMBIT_%_ROLE' THEN val  -- Municipality roles see their own data
        ELSE CONCAT(SUBSTR(val, 1, 6), '-XXXX')            -- Mask last 4 digits
    END;

-- Name Masking
CREATE OR REPLACE MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() LIKE 'KOMBIT_%_ROLE' THEN val
        ELSE CONCAT(SUBSTR(val, 1, 1), '****')
    END;

-- Address Masking
CREATE OR REPLACE MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() LIKE 'KOMBIT_%_ROLE' THEN val
        ELSE '*** MASKED ***'
    END;

-- Phone Masking
CREATE OR REPLACE MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() LIKE 'KOMBIT_%_ROLE' THEN val
        ELSE CONCAT('+45 XX XX ', SUBSTR(val, -2))
    END;

-- Email Masking
CREATE OR REPLACE MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() LIKE 'KOMBIT_%_ROLE' THEN val
        ELSE CONCAT(SUBSTR(SPLIT_PART(val, '@', 1), 1, 2), '***@', SPLIT_PART(val, '@', 2))
    END;

-- Example: Apply to a table
-- ALTER TABLE schema.CITIZENS MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
