version: 2

sources:
  - name: raw
    database: KOMBIT_C_DBT
    schema: RAW
    tables:
      - name: citizens
        description: Raw citizen data from Danish municipalities
      - name: sager
        description: Raw case data (welfare, social services)
      - name: ydelser
        description: Raw benefits/services data
      - name: ejendomme
        description: Raw property data
