WITH source AS (
    SELECT * FROM {{ source('raw', 'citizens') }}
),

cleaned AS (
    SELECT
        CITIZEN_ID,
        KOMMUNE_ID,
        
        TRIM(UPPER(FORNAVN)) AS FORNAVN_CLEAN,
        TRIM(UPPER(EFTERNAVN)) AS EFTERNAVN_CLEAN,
        TRIM(UPPER(FORNAVN)) || ' ' || TRIM(UPPER(EFTERNAVN)) AS FULDE_NAVN_COMPUTED,
        
        CPR_NUMMER,
        
        TRIM(INITCAP(ADRESSE)) AS ADRESSE_STANDARDIZED,
        TRIM(UPPER(POSTNUMMER)) AS POSTNUMMER,
        TRIM(INITCAP(BY_NAVN)) AS BY_NAVN_STANDARDIZED,
        
        REGEXP_REPLACE(TELEFON, '[^0-9+]', '') AS TELEFON_NORMALIZED,
        LOWER(TRIM(EMAIL)) AS EMAIL_NORMALIZED,
        
        FOEDSELSDATO,
        DATEDIFF(YEAR, FOEDSELSDATO, CURRENT_DATE()) AS ALDER_AAR,
        
        CASE 
            WHEN DATEDIFF(YEAR, FOEDSELSDATO, CURRENT_DATE()) < 18 THEN 'BARN'
            WHEN DATEDIFF(YEAR, FOEDSELSDATO, CURRENT_DATE()) BETWEEN 18 AND 30 THEN 'UNG_VOKSEN'
            WHEN DATEDIFF(YEAR, FOEDSELSDATO, CURRENT_DATE()) BETWEEN 31 AND 50 THEN 'VOKSEN'
            WHEN DATEDIFF(YEAR, FOEDSELSDATO, CURRENT_DATE()) BETWEEN 51 AND 67 THEN 'SENIOR'
            ELSE 'AELDRE'
        END AS ALDERSGRUPPE,
        
        KOEN,
        CREATED_AT,
        DATEDIFF(DAY, CREATED_AT, CURRENT_DATE()) AS DAGE_SIDEN_OPRETTELSE,
        
        CURRENT_TIMESTAMP() AS TRANSFORMERET_TIDSPUNKT,
        'dbt_staging' AS TRANSFORM_KILDE
        
    FROM source
    WHERE CITIZEN_ID IS NOT NULL
)

SELECT * FROM cleaned
