--------------------------------------------------------------------------------
-- KOMBIT GOVERNANCE SETUP
-- Roles, Masking Policies, Row Access Policies
-- CRITICAL: All policies use CURRENT_ROLE() not IS_ROLE_IN_SESSION()
--------------------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;

--------------------------------------------------------------------------------
-- 1. CREATE GOVERNANCE DATABASE
--------------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS KOMBIT_GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS KOMBIT_GOVERNANCE.POLICIES;

--------------------------------------------------------------------------------
-- 2. CREATE ROLES HIERARCHY
--------------------------------------------------------------------------------

CREATE ROLE IF NOT EXISTS KOMBIT_ADMIN;
CREATE ROLE IF NOT EXISTS KOMBIT_DATA_STEWARD;
CREATE ROLE IF NOT EXISTS KOMBIT_ANALYST;
CREATE ROLE IF NOT EXISTS KOMBIT_AUDITOR;
CREATE ROLE IF NOT EXISTS KOMBIT_COPENHAGEN_ROLE;
CREATE ROLE IF NOT EXISTS KOMBIT_AARHUS_ROLE;
CREATE ROLE IF NOT EXISTS KOMBIT_ODENSE_ROLE;
CREATE ROLE IF NOT EXISTS KOMBIT_AALBORG_ROLE;
CREATE ROLE IF NOT EXISTS KOMBIT_ESBJERG_ROLE;

GRANT ROLE KOMBIT_ADMIN TO ROLE SYSADMIN;
GRANT ROLE KOMBIT_DATA_STEWARD TO ROLE KOMBIT_ADMIN;
GRANT ROLE KOMBIT_ANALYST TO ROLE KOMBIT_ADMIN;
GRANT ROLE KOMBIT_AUDITOR TO ROLE KOMBIT_ADMIN;
GRANT ROLE KOMBIT_COPENHAGEN_ROLE TO ROLE KOMBIT_ADMIN;
GRANT ROLE KOMBIT_AARHUS_ROLE TO ROLE KOMBIT_ADMIN;
GRANT ROLE KOMBIT_ODENSE_ROLE TO ROLE KOMBIT_ADMIN;
GRANT ROLE KOMBIT_AALBORG_ROLE TO ROLE KOMBIT_ADMIN;
GRANT ROLE KOMBIT_ESBJERG_ROLE TO ROLE KOMBIT_ADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KOMBIT_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KOMBIT_DATA_STEWARD;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KOMBIT_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KOMBIT_AUDITOR;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KOMBIT_AARHUS_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KOMBIT_ODENSE_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KOMBIT_AALBORG_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KOMBIT_ESBJERG_ROLE;

--------------------------------------------------------------------------------
-- 3. MASKING POLICIES (Using CURRENT_ROLE())
--------------------------------------------------------------------------------

USE SCHEMA KOMBIT_GOVERNANCE.POLICIES;

CREATE OR REPLACE MASKING POLICY CPR_MASK AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() IN ('KOMBIT_COPENHAGEN_ROLE', 'KOMBIT_AARHUS_ROLE', 'KOMBIT_ODENSE_ROLE', 'KOMBIT_AALBORG_ROLE', 'KOMBIT_ESBJERG_ROLE') THEN val
        WHEN CURRENT_ROLE() = 'KOMBIT_ANALYST' THEN 'XXXXXX-' || RIGHT(val, 4)
        ELSE '******-****'
    END;

CREATE OR REPLACE MASKING POLICY NAME_MASK AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() IN ('KOMBIT_COPENHAGEN_ROLE', 'KOMBIT_AARHUS_ROLE', 'KOMBIT_ODENSE_ROLE', 'KOMBIT_AALBORG_ROLE', 'KOMBIT_ESBJERG_ROLE') THEN val
        WHEN CURRENT_ROLE() = 'KOMBIT_ANALYST' THEN LEFT(val, 1) || '****'
        ELSE '****'
    END;

CREATE OR REPLACE MASKING POLICY ADDRESS_MASK AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() IN ('KOMBIT_COPENHAGEN_ROLE', 'KOMBIT_AARHUS_ROLE', 'KOMBIT_ODENSE_ROLE', 'KOMBIT_AALBORG_ROLE', 'KOMBIT_ESBJERG_ROLE') THEN val
        WHEN CURRENT_ROLE() = 'KOMBIT_ANALYST' THEN SPLIT_PART(val, ' ', 1) || ' ***'
        ELSE '*** Masked ***'
    END;

CREATE OR REPLACE MASKING POLICY PHONE_MASK AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() IN ('KOMBIT_COPENHAGEN_ROLE', 'KOMBIT_AARHUS_ROLE', 'KOMBIT_ODENSE_ROLE', 'KOMBIT_AALBORG_ROLE', 'KOMBIT_ESBJERG_ROLE') THEN val
        WHEN CURRENT_ROLE() = 'KOMBIT_ANALYST' THEN '+45 XX XX ' || RIGHT(val, 2)
        ELSE '+45 XX XX XX'
    END;

CREATE OR REPLACE MASKING POLICY EMAIL_MASK AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD') THEN val
        WHEN CURRENT_ROLE() IN ('KOMBIT_COPENHAGEN_ROLE', 'KOMBIT_AARHUS_ROLE', 'KOMBIT_ODENSE_ROLE', 'KOMBIT_AALBORG_ROLE', 'KOMBIT_ESBJERG_ROLE') THEN val
        WHEN CURRENT_ROLE() = 'KOMBIT_ANALYST' THEN LEFT(SPLIT_PART(val, '@', 1), 2) || '***@' || SPLIT_PART(val, '@', 2)
        ELSE '***@***.dk'
    END;

--------------------------------------------------------------------------------
-- 4. ROW ACCESS POLICY (Using CURRENT_ROLE())
--------------------------------------------------------------------------------

CREATE OR REPLACE ROW ACCESS POLICY KOMMUNE_DATA_ACCESS AS (kommune_id VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'KOMBIT_ADMIN', 'KOMBIT_DATA_STEWARD', 'KOMBIT_ANALYST', 'KOMBIT_AUDITOR') THEN TRUE
        WHEN CURRENT_ROLE() = 'KOMBIT_COPENHAGEN_ROLE' AND kommune_id = 'COPENHAGEN' THEN TRUE
        WHEN CURRENT_ROLE() = 'KOMBIT_AARHUS_ROLE' AND kommune_id = 'AARHUS' THEN TRUE
        WHEN CURRENT_ROLE() = 'KOMBIT_ODENSE_ROLE' AND kommune_id = 'ODENSE' THEN TRUE
        WHEN CURRENT_ROLE() = 'KOMBIT_AALBORG_ROLE' AND kommune_id = 'AALBORG' THEN TRUE
        WHEN CURRENT_ROLE() = 'KOMBIT_ESBJERG_ROLE' AND kommune_id = 'ESBJERG' THEN TRUE
        ELSE FALSE
    END;

--------------------------------------------------------------------------------
-- 5. GRANT GOVERNANCE USAGE
--------------------------------------------------------------------------------

GRANT USAGE ON DATABASE KOMBIT_GOVERNANCE TO ROLE KOMBIT_ADMIN;
GRANT USAGE ON DATABASE KOMBIT_GOVERNANCE TO ROLE KOMBIT_DATA_STEWARD;
GRANT USAGE ON SCHEMA KOMBIT_GOVERNANCE.POLICIES TO ROLE KOMBIT_ADMIN;
GRANT USAGE ON SCHEMA KOMBIT_GOVERNANCE.POLICIES TO ROLE KOMBIT_DATA_STEWARD;
