--------------------------------------------------------------------------------
-- PATTERN A: Bottom-Up Aggregation
-- 5 Municipality DBs → 1 Aggregated DB with Dynamic Tables
-- Includes RLS and Masking on aggregated Dynamic Tables
--------------------------------------------------------------------------------

USE ROLE SYSADMIN;

--------------------------------------------------------------------------------
-- 1. CREATE MUNICIPALITY DATABASES
--------------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS KOMBIT_A_COPENHAGEN;
CREATE DATABASE IF NOT EXISTS KOMBIT_A_AARHUS;
CREATE DATABASE IF NOT EXISTS KOMBIT_A_ODENSE;
CREATE DATABASE IF NOT EXISTS KOMBIT_A_AALBORG;
CREATE DATABASE IF NOT EXISTS KOMBIT_A_ESBJERG;
CREATE DATABASE IF NOT EXISTS KOMBIT_A_AGGREGATED;

--------------------------------------------------------------------------------
-- 2. CREATE SCHEMAS IN EACH MUNICIPALITY DB
--------------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS KOMBIT_A_COPENHAGEN.RAW;
CREATE SCHEMA IF NOT EXISTS KOMBIT_A_AARHUS.RAW;
CREATE SCHEMA IF NOT EXISTS KOMBIT_A_ODENSE.RAW;
CREATE SCHEMA IF NOT EXISTS KOMBIT_A_AALBORG.RAW;
CREATE SCHEMA IF NOT EXISTS KOMBIT_A_ESBJERG.RAW;
CREATE SCHEMA IF NOT EXISTS KOMBIT_A_AGGREGATED.DYNAMIC_TABLES;

--------------------------------------------------------------------------------
-- 3. CREATE RAW TABLES IN EACH MUNICIPALITY (Danish column names)
--------------------------------------------------------------------------------

CREATE OR REPLACE TABLE KOMBIT_A_COPENHAGEN.RAW.CITIZENS (
    CITIZEN_ID VARCHAR(36),
    CPR_NUMMER VARCHAR(11),
    FORNAVN VARCHAR(100),
    EFTERNAVN VARCHAR(100),
    FULDE_NAVN VARCHAR(200),
    FOEDSELSDATO DATE,
    KOEN VARCHAR(10),
    ADRESSE VARCHAR(200),
    POSTNUMMER VARCHAR(4),
    BY_NAVN VARCHAR(100),
    KOMMUNE_ID VARCHAR(50) DEFAULT 'COPENHAGEN',
    TELEFON VARCHAR(20),
    EMAIL VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE KOMBIT_A_COPENHAGEN.RAW.SAGER (
    SAG_ID VARCHAR(36),
    SAGSNUMMER VARCHAR(20),
    CITIZEN_ID VARCHAR(36),
    CPR_NUMMER VARCHAR(11),
    SAG_TYPE VARCHAR(50),
    SAG_STATUS VARCHAR(30),
    OPRETTET_DATO DATE,
    AFSLUTTET_DATO DATE,
    SAGSBEHANDLER VARCHAR(100),
    KOMMUNE_ID VARCHAR(50) DEFAULT 'COPENHAGEN',
    BESKRIVELSE TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE KOMBIT_A_COPENHAGEN.RAW.YDELSER (
    YDELSE_ID VARCHAR(36),
    YDELSESNUMMER VARCHAR(20),
    CITIZEN_ID VARCHAR(36),
    CPR_NUMMER VARCHAR(11),
    YDELSE_TYPE VARCHAR(50),
    BELOEB NUMBER(12,2),
    UDBETALING_DATO DATE,
    PERIODE_START DATE,
    PERIODE_SLUT DATE,
    STATUS VARCHAR(30),
    KOMMUNE_ID VARCHAR(50) DEFAULT 'COPENHAGEN',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE KOMBIT_A_COPENHAGEN.RAW.EJENDOMME (
    EJENDOM_ID VARCHAR(36),
    MATRIKELNUMMER VARCHAR(20),
    EJER_CPR VARCHAR(11),
    ADRESSE VARCHAR(200),
    POSTNUMMER VARCHAR(4),
    BY_NAVN VARCHAR(100),
    EJENDOMSTYPE VARCHAR(50),
    VURDERING NUMBER(15,2),
    AREAL_M2 INT,
    KOMMUNE_ID VARCHAR(50) DEFAULT 'COPENHAGEN',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Clone structure to other municipalities
CREATE OR REPLACE TABLE KOMBIT_A_AARHUS.RAW.CITIZENS CLONE KOMBIT_A_COPENHAGEN.RAW.CITIZENS;
CREATE OR REPLACE TABLE KOMBIT_A_AARHUS.RAW.SAGER CLONE KOMBIT_A_COPENHAGEN.RAW.SAGER;
CREATE OR REPLACE TABLE KOMBIT_A_AARHUS.RAW.YDELSER CLONE KOMBIT_A_COPENHAGEN.RAW.YDELSER;
CREATE OR REPLACE TABLE KOMBIT_A_AARHUS.RAW.EJENDOMME CLONE KOMBIT_A_COPENHAGEN.RAW.EJENDOMME;

CREATE OR REPLACE TABLE KOMBIT_A_ODENSE.RAW.CITIZENS CLONE KOMBIT_A_COPENHAGEN.RAW.CITIZENS;
CREATE OR REPLACE TABLE KOMBIT_A_ODENSE.RAW.SAGER CLONE KOMBIT_A_COPENHAGEN.RAW.SAGER;
CREATE OR REPLACE TABLE KOMBIT_A_ODENSE.RAW.YDELSER CLONE KOMBIT_A_COPENHAGEN.RAW.YDELSER;
CREATE OR REPLACE TABLE KOMBIT_A_ODENSE.RAW.EJENDOMME CLONE KOMBIT_A_COPENHAGEN.RAW.EJENDOMME;

CREATE OR REPLACE TABLE KOMBIT_A_AALBORG.RAW.CITIZENS CLONE KOMBIT_A_COPENHAGEN.RAW.CITIZENS;
CREATE OR REPLACE TABLE KOMBIT_A_AALBORG.RAW.SAGER CLONE KOMBIT_A_COPENHAGEN.RAW.SAGER;
CREATE OR REPLACE TABLE KOMBIT_A_AALBORG.RAW.YDELSER CLONE KOMBIT_A_COPENHAGEN.RAW.YDELSER;
CREATE OR REPLACE TABLE KOMBIT_A_AALBORG.RAW.EJENDOMME CLONE KOMBIT_A_COPENHAGEN.RAW.EJENDOMME;

CREATE OR REPLACE TABLE KOMBIT_A_ESBJERG.RAW.CITIZENS CLONE KOMBIT_A_COPENHAGEN.RAW.CITIZENS;
CREATE OR REPLACE TABLE KOMBIT_A_ESBJERG.RAW.SAGER CLONE KOMBIT_A_COPENHAGEN.RAW.SAGER;
CREATE OR REPLACE TABLE KOMBIT_A_ESBJERG.RAW.YDELSER CLONE KOMBIT_A_COPENHAGEN.RAW.YDELSER;
CREATE OR REPLACE TABLE KOMBIT_A_ESBJERG.RAW.EJENDOMME CLONE KOMBIT_A_COPENHAGEN.RAW.EJENDOMME;

-- Update default KOMMUNE_ID for each municipality
ALTER TABLE KOMBIT_A_AARHUS.RAW.CITIZENS ALTER COLUMN KOMMUNE_ID SET DEFAULT 'AARHUS';
ALTER TABLE KOMBIT_A_AARHUS.RAW.SAGER ALTER COLUMN KOMMUNE_ID SET DEFAULT 'AARHUS';
ALTER TABLE KOMBIT_A_AARHUS.RAW.YDELSER ALTER COLUMN KOMMUNE_ID SET DEFAULT 'AARHUS';
ALTER TABLE KOMBIT_A_AARHUS.RAW.EJENDOMME ALTER COLUMN KOMMUNE_ID SET DEFAULT 'AARHUS';

ALTER TABLE KOMBIT_A_ODENSE.RAW.CITIZENS ALTER COLUMN KOMMUNE_ID SET DEFAULT 'ODENSE';
ALTER TABLE KOMBIT_A_ODENSE.RAW.SAGER ALTER COLUMN KOMMUNE_ID SET DEFAULT 'ODENSE';
ALTER TABLE KOMBIT_A_ODENSE.RAW.YDELSER ALTER COLUMN KOMMUNE_ID SET DEFAULT 'ODENSE';
ALTER TABLE KOMBIT_A_ODENSE.RAW.EJENDOMME ALTER COLUMN KOMMUNE_ID SET DEFAULT 'ODENSE';

ALTER TABLE KOMBIT_A_AALBORG.RAW.CITIZENS ALTER COLUMN KOMMUNE_ID SET DEFAULT 'AALBORG';
ALTER TABLE KOMBIT_A_AALBORG.RAW.SAGER ALTER COLUMN KOMMUNE_ID SET DEFAULT 'AALBORG';
ALTER TABLE KOMBIT_A_AALBORG.RAW.YDELSER ALTER COLUMN KOMMUNE_ID SET DEFAULT 'AALBORG';
ALTER TABLE KOMBIT_A_AALBORG.RAW.EJENDOMME ALTER COLUMN KOMMUNE_ID SET DEFAULT 'AALBORG';

ALTER TABLE KOMBIT_A_ESBJERG.RAW.CITIZENS ALTER COLUMN KOMMUNE_ID SET DEFAULT 'ESBJERG';
ALTER TABLE KOMBIT_A_ESBJERG.RAW.SAGER ALTER COLUMN KOMMUNE_ID SET DEFAULT 'ESBJERG';
ALTER TABLE KOMBIT_A_ESBJERG.RAW.YDELSER ALTER COLUMN KOMMUNE_ID SET DEFAULT 'ESBJERG';
ALTER TABLE KOMBIT_A_ESBJERG.RAW.EJENDOMME ALTER COLUMN KOMMUNE_ID SET DEFAULT 'ESBJERG';

--------------------------------------------------------------------------------
-- 4. CREATE AGGREGATED DYNAMIC TABLES
--------------------------------------------------------------------------------

CREATE OR REPLACE DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT * FROM KOMBIT_A_COPENHAGEN.RAW.CITIZENS
UNION ALL
SELECT * FROM KOMBIT_A_AARHUS.RAW.CITIZENS
UNION ALL
SELECT * FROM KOMBIT_A_ODENSE.RAW.CITIZENS
UNION ALL
SELECT * FROM KOMBIT_A_AALBORG.RAW.CITIZENS
UNION ALL
SELECT * FROM KOMBIT_A_ESBJERG.RAW.CITIZENS;

CREATE OR REPLACE DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_SAGER
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT * FROM KOMBIT_A_COPENHAGEN.RAW.SAGER
UNION ALL
SELECT * FROM KOMBIT_A_AARHUS.RAW.SAGER
UNION ALL
SELECT * FROM KOMBIT_A_ODENSE.RAW.SAGER
UNION ALL
SELECT * FROM KOMBIT_A_AALBORG.RAW.SAGER
UNION ALL
SELECT * FROM KOMBIT_A_ESBJERG.RAW.SAGER;

CREATE OR REPLACE DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_YDELSER
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT * FROM KOMBIT_A_COPENHAGEN.RAW.YDELSER
UNION ALL
SELECT * FROM KOMBIT_A_AARHUS.RAW.YDELSER
UNION ALL
SELECT * FROM KOMBIT_A_ODENSE.RAW.YDELSER
UNION ALL
SELECT * FROM KOMBIT_A_AALBORG.RAW.YDELSER
UNION ALL
SELECT * FROM KOMBIT_A_ESBJERG.RAW.YDELSER;

CREATE OR REPLACE DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_EJENDOMME
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT * FROM KOMBIT_A_COPENHAGEN.RAW.EJENDOMME
UNION ALL
SELECT * FROM KOMBIT_A_AARHUS.RAW.EJENDOMME
UNION ALL
SELECT * FROM KOMBIT_A_ODENSE.RAW.EJENDOMME
UNION ALL
SELECT * FROM KOMBIT_A_AALBORG.RAW.EJENDOMME
UNION ALL
SELECT * FROM KOMBIT_A_ESBJERG.RAW.EJENDOMME;

--------------------------------------------------------------------------------
-- 5. APPLY MASKING POLICIES TO DYNAMIC TABLES
--------------------------------------------------------------------------------

ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS 
    MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS 
    MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS 
    MODIFY COLUMN EFTERNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS 
    MODIFY COLUMN FULDE_NAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS 
    MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;
ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS 
    MODIFY COLUMN TELEFON SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK;
ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS 
    MODIFY COLUMN EMAIL SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK;

ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_SAGER 
    MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;

ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_YDELSER 
    MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;

ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_EJENDOMME 
    MODIFY COLUMN EJER_CPR SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_EJENDOMME 
    MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;

--------------------------------------------------------------------------------
-- 6. APPLY ROW ACCESS POLICIES TO DYNAMIC TABLES
--------------------------------------------------------------------------------

ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS 
    ADD ROW ACCESS POLICY KOMBIT_GOVERNANCE.POLICIES.KOMMUNE_DATA_ACCESS ON (KOMMUNE_ID);
ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_SAGER 
    ADD ROW ACCESS POLICY KOMBIT_GOVERNANCE.POLICIES.KOMMUNE_DATA_ACCESS ON (KOMMUNE_ID);
ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_YDELSER 
    ADD ROW ACCESS POLICY KOMBIT_GOVERNANCE.POLICIES.KOMMUNE_DATA_ACCESS ON (KOMMUNE_ID);
ALTER TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_EJENDOMME 
    ADD ROW ACCESS POLICY KOMBIT_GOVERNANCE.POLICIES.KOMMUNE_DATA_ACCESS ON (KOMMUNE_ID);

--------------------------------------------------------------------------------
-- 7. GRANT ACCESS TO ROLES
--------------------------------------------------------------------------------

GRANT USAGE ON DATABASE KOMBIT_A_AGGREGATED TO ROLE KOMBIT_ADMIN;
GRANT USAGE ON DATABASE KOMBIT_A_AGGREGATED TO ROLE KOMBIT_DATA_STEWARD;
GRANT USAGE ON DATABASE KOMBIT_A_AGGREGATED TO ROLE KOMBIT_ANALYST;
GRANT USAGE ON DATABASE KOMBIT_A_AGGREGATED TO ROLE KOMBIT_AUDITOR;
GRANT USAGE ON DATABASE KOMBIT_A_AGGREGATED TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT USAGE ON DATABASE KOMBIT_A_AGGREGATED TO ROLE KOMBIT_AARHUS_ROLE;
GRANT USAGE ON DATABASE KOMBIT_A_AGGREGATED TO ROLE KOMBIT_ODENSE_ROLE;
GRANT USAGE ON DATABASE KOMBIT_A_AGGREGATED TO ROLE KOMBIT_AALBORG_ROLE;
GRANT USAGE ON DATABASE KOMBIT_A_AGGREGATED TO ROLE KOMBIT_ESBJERG_ROLE;

GRANT USAGE ON SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_ADMIN;
GRANT USAGE ON SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_DATA_STEWARD;
GRANT USAGE ON SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_ANALYST;
GRANT USAGE ON SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_AUDITOR;
GRANT USAGE ON SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT USAGE ON SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_AARHUS_ROLE;
GRANT USAGE ON SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_ODENSE_ROLE;
GRANT USAGE ON SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_AALBORG_ROLE;
GRANT USAGE ON SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_ESBJERG_ROLE;

GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_ADMIN;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_DATA_STEWARD;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_AUDITOR;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_AARHUS_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_ODENSE_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_AALBORG_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA KOMBIT_A_AGGREGATED.DYNAMIC_TABLES TO ROLE KOMBIT_ESBJERG_ROLE;
