--------------------------------------------------------------------------------
-- PATTERN C: dbt-driven Transformations
-- Setup database, schemas, and RAW data
-- dbt will create STAGING views and MART tables
--------------------------------------------------------------------------------

USE ROLE SYSADMIN;

--------------------------------------------------------------------------------
-- 1. CREATE DATABASE AND SCHEMAS
--------------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS KOMBIT_C_DBT;

CREATE SCHEMA IF NOT EXISTS KOMBIT_C_DBT.RAW;
CREATE SCHEMA IF NOT EXISTS KOMBIT_C_DBT.STAGING;
CREATE SCHEMA IF NOT EXISTS KOMBIT_C_DBT.COPENHAGEN;
CREATE SCHEMA IF NOT EXISTS KOMBIT_C_DBT.AARHUS;
CREATE SCHEMA IF NOT EXISTS KOMBIT_C_DBT.ODENSE;
CREATE SCHEMA IF NOT EXISTS KOMBIT_C_DBT.AALBORG;
CREATE SCHEMA IF NOT EXISTS KOMBIT_C_DBT.ESBJERG;
CREATE SCHEMA IF NOT EXISTS KOMBIT_C_DBT.ANALYTICS;

--------------------------------------------------------------------------------
-- 2. CREATE RAW TABLES (Source for dbt)
--------------------------------------------------------------------------------

CREATE OR REPLACE TABLE KOMBIT_C_DBT.RAW.CITIZENS (
    CITIZEN_ID VARCHAR(36),
    CPR_NUMMER VARCHAR(11),
    FORNAVN VARCHAR(100),
    EFTERNAVN VARCHAR(100),
    FULDE_NAVN VARCHAR(200),
    FOEDSELSDATO DATE,
    KOEN VARCHAR(10),
    ADRESSE VARCHAR(200),
    POSTNUMMER VARCHAR(4),
    BY_NAVN VARCHAR(100),
    KOMMUNE_ID VARCHAR(50),
    TELEFON VARCHAR(20),
    EMAIL VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE KOMBIT_C_DBT.RAW.SAGER (
    SAG_ID VARCHAR(36),
    SAGSNUMMER VARCHAR(20),
    CITIZEN_ID VARCHAR(36),
    CPR_NUMMER VARCHAR(11),
    SAG_TYPE VARCHAR(50),
    SAG_STATUS VARCHAR(30),
    OPRETTET_DATO DATE,
    AFSLUTTET_DATO DATE,
    SAGSBEHANDLER VARCHAR(100),
    KOMMUNE_ID VARCHAR(50),
    BESKRIVELSE TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE KOMBIT_C_DBT.RAW.YDELSER (
    YDELSE_ID VARCHAR(36),
    YDELSESNUMMER VARCHAR(20),
    CITIZEN_ID VARCHAR(36),
    CPR_NUMMER VARCHAR(11),
    YDELSE_TYPE VARCHAR(50),
    BELOEB NUMBER(12,2),
    UDBETALING_DATO DATE,
    PERIODE_START DATE,
    PERIODE_SLUT DATE,
    STATUS VARCHAR(30),
    KOMMUNE_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE KOMBIT_C_DBT.RAW.EJENDOMME (
    EJENDOM_ID VARCHAR(36),
    MATRIKELNUMMER VARCHAR(20),
    EJER_CPR VARCHAR(11),
    ADRESSE VARCHAR(200),
    POSTNUMMER VARCHAR(4),
    BY_NAVN VARCHAR(100),
    EJENDOMSTYPE VARCHAR(50),
    VURDERING NUMBER(15,2),
    AREAL_M2 INT,
    KOMMUNE_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

--------------------------------------------------------------------------------
-- 3. APPLY MASKING POLICIES TO RAW TABLES
--------------------------------------------------------------------------------

ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS 
    MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS 
    MODIFY COLUMN FORNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS 
    MODIFY COLUMN EFTERNAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS 
    MODIFY COLUMN FULDE_NAVN SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.NAME_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS 
    MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS 
    MODIFY COLUMN TELEFON SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.PHONE_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS 
    MODIFY COLUMN EMAIL SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.EMAIL_MASK;

ALTER TABLE KOMBIT_C_DBT.RAW.SAGER 
    MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;

ALTER TABLE KOMBIT_C_DBT.RAW.YDELSER 
    MODIFY COLUMN CPR_NUMMER SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;

ALTER TABLE KOMBIT_C_DBT.RAW.EJENDOMME 
    MODIFY COLUMN EJER_CPR SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.CPR_MASK;
ALTER TABLE KOMBIT_C_DBT.RAW.EJENDOMME 
    MODIFY COLUMN ADRESSE SET MASKING POLICY KOMBIT_GOVERNANCE.POLICIES.ADDRESS_MASK;

--------------------------------------------------------------------------------
-- 4. APPLY ROW ACCESS POLICIES TO RAW TABLES
--------------------------------------------------------------------------------

ALTER TABLE KOMBIT_C_DBT.RAW.CITIZENS 
    ADD ROW ACCESS POLICY KOMBIT_GOVERNANCE.POLICIES.KOMMUNE_DATA_ACCESS ON (KOMMUNE_ID);
ALTER TABLE KOMBIT_C_DBT.RAW.SAGER 
    ADD ROW ACCESS POLICY KOMBIT_GOVERNANCE.POLICIES.KOMMUNE_DATA_ACCESS ON (KOMMUNE_ID);
ALTER TABLE KOMBIT_C_DBT.RAW.YDELSER 
    ADD ROW ACCESS POLICY KOMBIT_GOVERNANCE.POLICIES.KOMMUNE_DATA_ACCESS ON (KOMMUNE_ID);
ALTER TABLE KOMBIT_C_DBT.RAW.EJENDOMME 
    ADD ROW ACCESS POLICY KOMBIT_GOVERNANCE.POLICIES.KOMMUNE_DATA_ACCESS ON (KOMMUNE_ID);

--------------------------------------------------------------------------------
-- 5. GRANT ACCESS TO ROLES
--------------------------------------------------------------------------------

GRANT USAGE ON DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ADMIN;
GRANT USAGE ON DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_DATA_STEWARD;
GRANT USAGE ON DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ANALYST;
GRANT USAGE ON DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AUDITOR;
GRANT USAGE ON DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT USAGE ON DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AARHUS_ROLE;
GRANT USAGE ON DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ODENSE_ROLE;
GRANT USAGE ON DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AALBORG_ROLE;
GRANT USAGE ON DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ESBJERG_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_DATA_STEWARD;
GRANT USAGE ON ALL SCHEMAS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AUDITOR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AARHUS_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ODENSE_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AALBORG_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ESBJERG_ROLE;

GRANT SELECT ON ALL TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ADMIN;
GRANT SELECT ON ALL TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_DATA_STEWARD;
GRANT SELECT ON ALL TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AUDITOR;
GRANT SELECT ON ALL TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AARHUS_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ODENSE_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AALBORG_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ESBJERG_ROLE;

GRANT SELECT ON FUTURE TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ADMIN;
GRANT SELECT ON FUTURE TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_DATA_STEWARD;
GRANT SELECT ON FUTURE TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ANALYST;
GRANT SELECT ON FUTURE TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AARHUS_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ODENSE_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AALBORG_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ESBJERG_ROLE;

GRANT SELECT ON FUTURE VIEWS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ADMIN;
GRANT SELECT ON FUTURE VIEWS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_DATA_STEWARD;
GRANT SELECT ON FUTURE VIEWS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AARHUS_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ODENSE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_AALBORG_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE KOMBIT_C_DBT TO ROLE KOMBIT_ESBJERG_ROLE;
