--------------------------------------------------------------------------------
-- SAMPLE DATA GENERATOR
-- Creates realistic Danish municipality test data
-- Run after 02_pattern_a.sql and 03_pattern_c_setup.sql
--------------------------------------------------------------------------------

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

--------------------------------------------------------------------------------
-- HELPER: Generate Danish Names and Data
--------------------------------------------------------------------------------

CREATE OR REPLACE TEMPORARY TABLE DANISH_FIRST_NAMES AS
SELECT column1 AS FORNAVN, column2 AS KOEN FROM VALUES
('Anders', 'M'), ('Mette', 'F'), ('Lars', 'M'), ('Anne', 'F'), ('Peter', 'M'),
('Maria', 'F'), ('Jens', 'M'), ('Sofie', 'F'), ('Henrik', 'M'), ('Louise', 'F'),
('Thomas', 'M'), ('Emma', 'F'), ('Michael', 'M'), ('Ida', 'F'), ('Kristian', 'M'),
('Freja', 'F'), ('Rasmus', 'M'), ('Clara', 'F'), ('Søren', 'M'), ('Maja', 'F'),
('Niels', 'M'), ('Alma', 'F'), ('Martin', 'M'), ('Laura', 'F'), ('Christian', 'M'),
('Olivia', 'F'), ('Jacob', 'M'), ('Victoria', 'F'), ('Frederik', 'M'), ('Isabella', 'F');

CREATE OR REPLACE TEMPORARY TABLE DANISH_LAST_NAMES AS
SELECT column1 AS EFTERNAVN FROM VALUES
('Jensen'), ('Nielsen'), ('Hansen'), ('Pedersen'), ('Andersen'),
('Christensen'), ('Larsen'), ('Sørensen'), ('Rasmussen'), ('Jørgensen'),
('Petersen'), ('Madsen'), ('Kristensen'), ('Olsen'), ('Thomsen'),
('Christiansen'), ('Poulsen'), ('Johansen'), ('Møller'), ('Mortensen');

CREATE OR REPLACE TEMPORARY TABLE DANISH_STREETS AS
SELECT column1 AS STREET FROM VALUES
('Hovedgaden'), ('Strandvejen'), ('Skovvej'), ('Kirkevej'), ('Nørregade'),
('Østerbrogade'), ('Vestergade'), ('Søndergade'), ('Havnevej'), ('Rosenvej'),
('Parkvej'), ('Engvej'), ('Bakkevej'), ('Møllevej'), ('Skolegade');

CREATE OR REPLACE TEMPORARY TABLE COPENHAGEN_AREAS AS
SELECT column1 AS BY_NAVN, column2 AS POSTNUMMER FROM VALUES
('København K', '1000'), ('København V', '1500'), ('Frederiksberg', '2000'),
('Østerbro', '2100'), ('Nørrebro', '2200'), ('Vanløse', '2720'), ('Valby', '2500');

CREATE OR REPLACE TEMPORARY TABLE AARHUS_AREAS AS
SELECT column1 AS BY_NAVN, column2 AS POSTNUMMER FROM VALUES
('Aarhus C', '8000'), ('Aarhus N', '8200'), ('Aarhus V', '8210'),
('Højbjerg', '8270'), ('Brabrand', '8220'), ('Viby J', '8260');

CREATE OR REPLACE TEMPORARY TABLE ODENSE_AREAS AS
SELECT column1 AS BY_NAVN, column2 AS POSTNUMMER FROM VALUES
('Odense C', '5000'), ('Odense M', '5200'), ('Odense SØ', '5220'),
('Odense NV', '5210'), ('Dalum', '5250'), ('Bellinge', '5240');

CREATE OR REPLACE TEMPORARY TABLE AALBORG_AREAS AS
SELECT column1 AS BY_NAVN, column2 AS POSTNUMMER FROM VALUES
('Aalborg', '9000'), ('Aalborg SV', '9200'), ('Aalborg Øst', '9220'),
('Nørresundby', '9400'), ('Svenstrup', '9230'), ('Sulsted', '9381');

CREATE OR REPLACE TEMPORARY TABLE ESBJERG_AREAS AS
SELECT column1 AS BY_NAVN, column2 AS POSTNUMMER FROM VALUES
('Esbjerg', '6700'), ('Esbjerg Ø', '6705'), ('Esbjerg N', '6715'),
('Bramming', '6740'), ('Tjæreborg', '6731'), ('Guldager', '6710');

--------------------------------------------------------------------------------
-- GENERATE DATA FOR PATTERN A (Individual Municipality DBs)
--------------------------------------------------------------------------------

INSERT INTO KOMBIT_A_COPENHAGEN.RAW.CITIZENS
SELECT 
    UUID_STRING() AS CITIZEN_ID,
    LPAD(FLOOR(UNIFORM(1,28,RANDOM()))::STRING, 2, '0') || 
    LPAD(FLOOR(UNIFORM(1,12,RANDOM()))::STRING, 2, '0') ||
    LPAD(MOD(FLOOR(UNIFORM(40,99,RANDOM())), 100)::STRING, 2, '0') || '-' ||
    LPAD(FLOOR(UNIFORM(1000,9999,RANDOM()))::STRING, 4, '0') AS CPR_NUMMER,
    fn.FORNAVN,
    ln.EFTERNAVN,
    fn.FORNAVN || ' ' || ln.EFTERNAVN AS FULDE_NAVN,
    DATEADD(DAY, -FLOOR(UNIFORM(6570, 29200, RANDOM())), CURRENT_DATE()) AS FOEDSELSDATO,
    fn.KOEN,
    st.STREET || ' ' || FLOOR(UNIFORM(1, 200, RANDOM()))::STRING AS ADRESSE,
    ca.POSTNUMMER,
    ca.BY_NAVN,
    'COPENHAGEN' AS KOMMUNE_ID,
    '+45 ' || LPAD(FLOOR(UNIFORM(20,99,RANDOM()))::STRING,2,'0') || ' ' ||
    LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0') || ' ' ||
    LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0') || ' ' ||
    LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0') AS TELEFON,
    LOWER(fn.FORNAVN) || '.' || LOWER(ln.EFTERNAVN) || FLOOR(UNIFORM(1,999,RANDOM()))::STRING || '@email.dk' AS EMAIL,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 100000)) g
CROSS JOIN (SELECT FORNAVN, KOEN FROM DANISH_FIRST_NAMES ORDER BY RANDOM() LIMIT 1) fn
CROSS JOIN (SELECT EFTERNAVN FROM DANISH_LAST_NAMES ORDER BY RANDOM() LIMIT 1) ln
CROSS JOIN (SELECT STREET FROM DANISH_STREETS ORDER BY RANDOM() LIMIT 1) st
CROSS JOIN (SELECT BY_NAVN, POSTNUMMER FROM COPENHAGEN_AREAS ORDER BY RANDOM() LIMIT 1) ca;

INSERT INTO KOMBIT_A_AARHUS.RAW.CITIZENS
SELECT 
    UUID_STRING(), 
    LPAD(FLOOR(UNIFORM(1,28,RANDOM()))::STRING, 2, '0') || LPAD(FLOOR(UNIFORM(1,12,RANDOM()))::STRING, 2, '0') || LPAD(MOD(FLOOR(UNIFORM(40,99,RANDOM())), 100)::STRING, 2, '0') || '-' || LPAD(FLOOR(UNIFORM(1000,9999,RANDOM()))::STRING, 4, '0'),
    fn.FORNAVN, ln.EFTERNAVN, fn.FORNAVN || ' ' || ln.EFTERNAVN,
    DATEADD(DAY, -FLOOR(UNIFORM(6570, 29200, RANDOM())), CURRENT_DATE()),
    fn.KOEN, st.STREET || ' ' || FLOOR(UNIFORM(1, 200, RANDOM()))::STRING,
    aa.POSTNUMMER, aa.BY_NAVN, 'AARHUS',
    '+45 ' || LPAD(FLOOR(UNIFORM(20,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0'),
    LOWER(fn.FORNAVN) || '.' || LOWER(ln.EFTERNAVN) || FLOOR(UNIFORM(1,999,RANDOM()))::STRING || '@email.dk',
    CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM TABLE(GENERATOR(ROWCOUNT => 100000)) g
CROSS JOIN (SELECT FORNAVN, KOEN FROM DANISH_FIRST_NAMES ORDER BY RANDOM() LIMIT 1) fn
CROSS JOIN (SELECT EFTERNAVN FROM DANISH_LAST_NAMES ORDER BY RANDOM() LIMIT 1) ln
CROSS JOIN (SELECT STREET FROM DANISH_STREETS ORDER BY RANDOM() LIMIT 1) st
CROSS JOIN (SELECT BY_NAVN, POSTNUMMER FROM AARHUS_AREAS ORDER BY RANDOM() LIMIT 1) aa;

INSERT INTO KOMBIT_A_ODENSE.RAW.CITIZENS
SELECT 
    UUID_STRING(), 
    LPAD(FLOOR(UNIFORM(1,28,RANDOM()))::STRING, 2, '0') || LPAD(FLOOR(UNIFORM(1,12,RANDOM()))::STRING, 2, '0') || LPAD(MOD(FLOOR(UNIFORM(40,99,RANDOM())), 100)::STRING, 2, '0') || '-' || LPAD(FLOOR(UNIFORM(1000,9999,RANDOM()))::STRING, 4, '0'),
    fn.FORNAVN, ln.EFTERNAVN, fn.FORNAVN || ' ' || ln.EFTERNAVN,
    DATEADD(DAY, -FLOOR(UNIFORM(6570, 29200, RANDOM())), CURRENT_DATE()),
    fn.KOEN, st.STREET || ' ' || FLOOR(UNIFORM(1, 200, RANDOM()))::STRING,
    oa.POSTNUMMER, oa.BY_NAVN, 'ODENSE',
    '+45 ' || LPAD(FLOOR(UNIFORM(20,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0'),
    LOWER(fn.FORNAVN) || '.' || LOWER(ln.EFTERNAVN) || FLOOR(UNIFORM(1,999,RANDOM()))::STRING || '@email.dk',
    CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM TABLE(GENERATOR(ROWCOUNT => 100000)) g
CROSS JOIN (SELECT FORNAVN, KOEN FROM DANISH_FIRST_NAMES ORDER BY RANDOM() LIMIT 1) fn
CROSS JOIN (SELECT EFTERNAVN FROM DANISH_LAST_NAMES ORDER BY RANDOM() LIMIT 1) ln
CROSS JOIN (SELECT STREET FROM DANISH_STREETS ORDER BY RANDOM() LIMIT 1) st
CROSS JOIN (SELECT BY_NAVN, POSTNUMMER FROM ODENSE_AREAS ORDER BY RANDOM() LIMIT 1) oa;

INSERT INTO KOMBIT_A_AALBORG.RAW.CITIZENS
SELECT 
    UUID_STRING(), 
    LPAD(FLOOR(UNIFORM(1,28,RANDOM()))::STRING, 2, '0') || LPAD(FLOOR(UNIFORM(1,12,RANDOM()))::STRING, 2, '0') || LPAD(MOD(FLOOR(UNIFORM(40,99,RANDOM())), 100)::STRING, 2, '0') || '-' || LPAD(FLOOR(UNIFORM(1000,9999,RANDOM()))::STRING, 4, '0'),
    fn.FORNAVN, ln.EFTERNAVN, fn.FORNAVN || ' ' || ln.EFTERNAVN,
    DATEADD(DAY, -FLOOR(UNIFORM(6570, 29200, RANDOM())), CURRENT_DATE()),
    fn.KOEN, st.STREET || ' ' || FLOOR(UNIFORM(1, 200, RANDOM()))::STRING,
    ala.POSTNUMMER, ala.BY_NAVN, 'AALBORG',
    '+45 ' || LPAD(FLOOR(UNIFORM(20,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0'),
    LOWER(fn.FORNAVN) || '.' || LOWER(ln.EFTERNAVN) || FLOOR(UNIFORM(1,999,RANDOM()))::STRING || '@email.dk',
    CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM TABLE(GENERATOR(ROWCOUNT => 100000)) g
CROSS JOIN (SELECT FORNAVN, KOEN FROM DANISH_FIRST_NAMES ORDER BY RANDOM() LIMIT 1) fn
CROSS JOIN (SELECT EFTERNAVN FROM DANISH_LAST_NAMES ORDER BY RANDOM() LIMIT 1) ln
CROSS JOIN (SELECT STREET FROM DANISH_STREETS ORDER BY RANDOM() LIMIT 1) st
CROSS JOIN (SELECT BY_NAVN, POSTNUMMER FROM AALBORG_AREAS ORDER BY RANDOM() LIMIT 1) ala;

INSERT INTO KOMBIT_A_ESBJERG.RAW.CITIZENS
SELECT 
    UUID_STRING(), 
    LPAD(FLOOR(UNIFORM(1,28,RANDOM()))::STRING, 2, '0') || LPAD(FLOOR(UNIFORM(1,12,RANDOM()))::STRING, 2, '0') || LPAD(MOD(FLOOR(UNIFORM(40,99,RANDOM())), 100)::STRING, 2, '0') || '-' || LPAD(FLOOR(UNIFORM(1000,9999,RANDOM()))::STRING, 4, '0'),
    fn.FORNAVN, ln.EFTERNAVN, fn.FORNAVN || ' ' || ln.EFTERNAVN,
    DATEADD(DAY, -FLOOR(UNIFORM(6570, 29200, RANDOM())), CURRENT_DATE()),
    fn.KOEN, st.STREET || ' ' || FLOOR(UNIFORM(1, 200, RANDOM()))::STRING,
    ea.POSTNUMMER, ea.BY_NAVN, 'ESBJERG',
    '+45 ' || LPAD(FLOOR(UNIFORM(20,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0') || ' ' || LPAD(FLOOR(UNIFORM(10,99,RANDOM()))::STRING,2,'0'),
    LOWER(fn.FORNAVN) || '.' || LOWER(ln.EFTERNAVN) || FLOOR(UNIFORM(1,999,RANDOM()))::STRING || '@email.dk',
    CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM TABLE(GENERATOR(ROWCOUNT => 100000)) g
CROSS JOIN (SELECT FORNAVN, KOEN FROM DANISH_FIRST_NAMES ORDER BY RANDOM() LIMIT 1) fn
CROSS JOIN (SELECT EFTERNAVN FROM DANISH_LAST_NAMES ORDER BY RANDOM() LIMIT 1) ln
CROSS JOIN (SELECT STREET FROM DANISH_STREETS ORDER BY RANDOM() LIMIT 1) st
CROSS JOIN (SELECT BY_NAVN, POSTNUMMER FROM ESBJERG_AREAS ORDER BY RANDOM() LIMIT 1) ea;

--------------------------------------------------------------------------------
-- GENERATE SAGER (Cases) FOR ALL MUNICIPALITIES
--------------------------------------------------------------------------------

CREATE OR REPLACE TEMPORARY TABLE SAG_TYPES AS
SELECT column1 AS SAG_TYPE FROM VALUES
('SOCIAL'), ('BESKAEFTIGELSE'), ('BOLIG'), ('SUNDHED'), ('BARN_FAMILIE'),
('AELDRE'), ('INTEGRATION'), ('HANDICAP'), ('PENSION'), ('UDDANNELSE');

CREATE OR REPLACE TEMPORARY TABLE SAG_STATUSES AS
SELECT column1 AS SAG_STATUS FROM VALUES
('AABEN'), ('LUKKET'), ('AFVENTER'), ('GODKENDT'), ('AFVIST');

INSERT INTO KOMBIT_A_COPENHAGEN.RAW.SAGER
SELECT 
    UUID_STRING() AS SAG_ID,
    'SAG-CPH-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0') AS SAGSNUMMER,
    c.CITIZEN_ID, c.CPR_NUMMER,
    st.SAG_TYPE, ss.SAG_STATUS,
    DATEADD(DAY, -FLOOR(UNIFORM(1, 365, RANDOM())), CURRENT_DATE()) AS OPRETTET_DATO,
    CASE WHEN ss.SAG_STATUS = 'LUKKET' THEN DATEADD(DAY, -FLOOR(UNIFORM(1, 30, RANDOM())), CURRENT_DATE()) ELSE NULL END AS AFSLUTTET_DATO,
    'Sagsbehandler ' || FLOOR(UNIFORM(1, 50, RANDOM()))::STRING AS SAGSBEHANDLER,
    'COPENHAGEN' AS KOMMUNE_ID,
    'Beskrivelse af sag' AS BESKRIVELSE,
    CURRENT_TIMESTAMP()
FROM KOMBIT_A_COPENHAGEN.RAW.CITIZENS c
CROSS JOIN (SELECT SAG_TYPE FROM SAG_TYPES ORDER BY RANDOM() LIMIT 1) st
CROSS JOIN (SELECT SAG_STATUS FROM SAG_STATUSES ORDER BY RANDOM() LIMIT 1) ss
WHERE UNIFORM(0, 1, RANDOM()) < 0.2
LIMIT 20000;

INSERT INTO KOMBIT_A_AARHUS.RAW.SAGER SELECT UUID_STRING(), 'SAG-AAR-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CITIZEN_ID, c.CPR_NUMMER, st.SAG_TYPE, ss.SAG_STATUS, DATEADD(DAY, -FLOOR(UNIFORM(1, 365, RANDOM())), CURRENT_DATE()), CASE WHEN ss.SAG_STATUS = 'LUKKET' THEN DATEADD(DAY, -FLOOR(UNIFORM(1, 30, RANDOM())), CURRENT_DATE()) ELSE NULL END, 'Sagsbehandler ' || FLOOR(UNIFORM(1, 50, RANDOM()))::STRING, 'AARHUS', 'Beskrivelse af sag', CURRENT_TIMESTAMP() FROM KOMBIT_A_AARHUS.RAW.CITIZENS c CROSS JOIN (SELECT SAG_TYPE FROM SAG_TYPES ORDER BY RANDOM() LIMIT 1) st CROSS JOIN (SELECT SAG_STATUS FROM SAG_STATUSES ORDER BY RANDOM() LIMIT 1) ss WHERE UNIFORM(0, 1, RANDOM()) < 0.2 LIMIT 20000;

INSERT INTO KOMBIT_A_ODENSE.RAW.SAGER SELECT UUID_STRING(), 'SAG-ODE-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CITIZEN_ID, c.CPR_NUMMER, st.SAG_TYPE, ss.SAG_STATUS, DATEADD(DAY, -FLOOR(UNIFORM(1, 365, RANDOM())), CURRENT_DATE()), CASE WHEN ss.SAG_STATUS = 'LUKKET' THEN DATEADD(DAY, -FLOOR(UNIFORM(1, 30, RANDOM())), CURRENT_DATE()) ELSE NULL END, 'Sagsbehandler ' || FLOOR(UNIFORM(1, 50, RANDOM()))::STRING, 'ODENSE', 'Beskrivelse af sag', CURRENT_TIMESTAMP() FROM KOMBIT_A_ODENSE.RAW.CITIZENS c CROSS JOIN (SELECT SAG_TYPE FROM SAG_TYPES ORDER BY RANDOM() LIMIT 1) st CROSS JOIN (SELECT SAG_STATUS FROM SAG_STATUSES ORDER BY RANDOM() LIMIT 1) ss WHERE UNIFORM(0, 1, RANDOM()) < 0.2 LIMIT 20000;

INSERT INTO KOMBIT_A_AALBORG.RAW.SAGER SELECT UUID_STRING(), 'SAG-AAL-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CITIZEN_ID, c.CPR_NUMMER, st.SAG_TYPE, ss.SAG_STATUS, DATEADD(DAY, -FLOOR(UNIFORM(1, 365, RANDOM())), CURRENT_DATE()), CASE WHEN ss.SAG_STATUS = 'LUKKET' THEN DATEADD(DAY, -FLOOR(UNIFORM(1, 30, RANDOM())), CURRENT_DATE()) ELSE NULL END, 'Sagsbehandler ' || FLOOR(UNIFORM(1, 50, RANDOM()))::STRING, 'AALBORG', 'Beskrivelse af sag', CURRENT_TIMESTAMP() FROM KOMBIT_A_AALBORG.RAW.CITIZENS c CROSS JOIN (SELECT SAG_TYPE FROM SAG_TYPES ORDER BY RANDOM() LIMIT 1) st CROSS JOIN (SELECT SAG_STATUS FROM SAG_STATUSES ORDER BY RANDOM() LIMIT 1) ss WHERE UNIFORM(0, 1, RANDOM()) < 0.2 LIMIT 20000;

INSERT INTO KOMBIT_A_ESBJERG.RAW.SAGER SELECT UUID_STRING(), 'SAG-ESB-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CITIZEN_ID, c.CPR_NUMMER, st.SAG_TYPE, ss.SAG_STATUS, DATEADD(DAY, -FLOOR(UNIFORM(1, 365, RANDOM())), CURRENT_DATE()), CASE WHEN ss.SAG_STATUS = 'LUKKET' THEN DATEADD(DAY, -FLOOR(UNIFORM(1, 30, RANDOM())), CURRENT_DATE()) ELSE NULL END, 'Sagsbehandler ' || FLOOR(UNIFORM(1, 50, RANDOM()))::STRING, 'ESBJERG', 'Beskrivelse af sag', CURRENT_TIMESTAMP() FROM KOMBIT_A_ESBJERG.RAW.CITIZENS c CROSS JOIN (SELECT SAG_TYPE FROM SAG_TYPES ORDER BY RANDOM() LIMIT 1) st CROSS JOIN (SELECT SAG_STATUS FROM SAG_STATUSES ORDER BY RANDOM() LIMIT 1) ss WHERE UNIFORM(0, 1, RANDOM()) < 0.2 LIMIT 20000;

--------------------------------------------------------------------------------
-- GENERATE YDELSER (Benefits) AND EJENDOMME (Properties) similarly
-- (Abbreviated for brevity - follow same pattern)
--------------------------------------------------------------------------------

CREATE OR REPLACE TEMPORARY TABLE YDELSE_TYPES AS
SELECT column1 AS YDELSE_TYPE FROM VALUES
('DAGPENGE'), ('PENSION'), ('BOERNETILSKUD'), ('BOLIGSTOETTE'), ('HANDICAP'),
('SUNDHED'), ('SU'), ('KONTANTHJAELP');

INSERT INTO KOMBIT_A_COPENHAGEN.RAW.YDELSER SELECT UUID_STRING(), 'YDE-CPH-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CITIZEN_ID, c.CPR_NUMMER, yt.YDELSE_TYPE, FLOOR(UNIFORM(1000, 25000, RANDOM())), DATEADD(DAY, -FLOOR(UNIFORM(1, 90, RANDOM())), CURRENT_DATE()), DATEADD(MONTH, -FLOOR(UNIFORM(1, 12, RANDOM())), CURRENT_DATE()), DATEADD(MONTH, FLOOR(UNIFORM(1, 12, RANDOM())), CURRENT_DATE()), 'AKTIV', 'COPENHAGEN', CURRENT_TIMESTAMP() FROM KOMBIT_A_COPENHAGEN.RAW.CITIZENS c CROSS JOIN (SELECT YDELSE_TYPE FROM YDELSE_TYPES ORDER BY RANDOM() LIMIT 1) yt WHERE UNIFORM(0, 1, RANDOM()) < 0.15 LIMIT 15000;
INSERT INTO KOMBIT_A_AARHUS.RAW.YDELSER SELECT UUID_STRING(), 'YDE-AAR-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CITIZEN_ID, c.CPR_NUMMER, yt.YDELSE_TYPE, FLOOR(UNIFORM(1000, 25000, RANDOM())), DATEADD(DAY, -FLOOR(UNIFORM(1, 90, RANDOM())), CURRENT_DATE()), DATEADD(MONTH, -FLOOR(UNIFORM(1, 12, RANDOM())), CURRENT_DATE()), DATEADD(MONTH, FLOOR(UNIFORM(1, 12, RANDOM())), CURRENT_DATE()), 'AKTIV', 'AARHUS', CURRENT_TIMESTAMP() FROM KOMBIT_A_AARHUS.RAW.CITIZENS c CROSS JOIN (SELECT YDELSE_TYPE FROM YDELSE_TYPES ORDER BY RANDOM() LIMIT 1) yt WHERE UNIFORM(0, 1, RANDOM()) < 0.15 LIMIT 15000;
INSERT INTO KOMBIT_A_ODENSE.RAW.YDELSER SELECT UUID_STRING(), 'YDE-ODE-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CITIZEN_ID, c.CPR_NUMMER, yt.YDELSE_TYPE, FLOOR(UNIFORM(1000, 25000, RANDOM())), DATEADD(DAY, -FLOOR(UNIFORM(1, 90, RANDOM())), CURRENT_DATE()), DATEADD(MONTH, -FLOOR(UNIFORM(1, 12, RANDOM())), CURRENT_DATE()), DATEADD(MONTH, FLOOR(UNIFORM(1, 12, RANDOM())), CURRENT_DATE()), 'AKTIV', 'ODENSE', CURRENT_TIMESTAMP() FROM KOMBIT_A_ODENSE.RAW.CITIZENS c CROSS JOIN (SELECT YDELSE_TYPE FROM YDELSE_TYPES ORDER BY RANDOM() LIMIT 1) yt WHERE UNIFORM(0, 1, RANDOM()) < 0.15 LIMIT 15000;
INSERT INTO KOMBIT_A_AALBORG.RAW.YDELSER SELECT UUID_STRING(), 'YDE-AAL-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CITIZEN_ID, c.CPR_NUMMER, yt.YDELSE_TYPE, FLOOR(UNIFORM(1000, 25000, RANDOM())), DATEADD(DAY, -FLOOR(UNIFORM(1, 90, RANDOM())), CURRENT_DATE()), DATEADD(MONTH, -FLOOR(UNIFORM(1, 12, RANDOM())), CURRENT_DATE()), DATEADD(MONTH, FLOOR(UNIFORM(1, 12, RANDOM())), CURRENT_DATE()), 'AKTIV', 'AALBORG', CURRENT_TIMESTAMP() FROM KOMBIT_A_AALBORG.RAW.CITIZENS c CROSS JOIN (SELECT YDELSE_TYPE FROM YDELSE_TYPES ORDER BY RANDOM() LIMIT 1) yt WHERE UNIFORM(0, 1, RANDOM()) < 0.15 LIMIT 15000;
INSERT INTO KOMBIT_A_ESBJERG.RAW.YDELSER SELECT UUID_STRING(), 'YDE-ESB-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CITIZEN_ID, c.CPR_NUMMER, yt.YDELSE_TYPE, FLOOR(UNIFORM(1000, 25000, RANDOM())), DATEADD(DAY, -FLOOR(UNIFORM(1, 90, RANDOM())), CURRENT_DATE()), DATEADD(MONTH, -FLOOR(UNIFORM(1, 12, RANDOM())), CURRENT_DATE()), DATEADD(MONTH, FLOOR(UNIFORM(1, 12, RANDOM())), CURRENT_DATE()), 'AKTIV', 'ESBJERG', CURRENT_TIMESTAMP() FROM KOMBIT_A_ESBJERG.RAW.CITIZENS c CROSS JOIN (SELECT YDELSE_TYPE FROM YDELSE_TYPES ORDER BY RANDOM() LIMIT 1) yt WHERE UNIFORM(0, 1, RANDOM()) < 0.15 LIMIT 15000;

CREATE OR REPLACE TEMPORARY TABLE EJENDOM_TYPES AS
SELECT column1 AS EJENDOMSTYPE FROM VALUES
('VILLA'), ('LEJLIGHED'), ('RAEKKEHUS'), ('SOMMERHUS'), ('LANDBRUG'), ('ERHVERV');

INSERT INTO KOMBIT_A_COPENHAGEN.RAW.EJENDOMME SELECT UUID_STRING(), 'MAT-CPH-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CPR_NUMMER, c.ADRESSE, c.POSTNUMMER, c.BY_NAVN, et.EJENDOMSTYPE, FLOOR(UNIFORM(500000, 15000000, RANDOM())), FLOOR(UNIFORM(50, 400, RANDOM())), 'COPENHAGEN', CURRENT_TIMESTAMP() FROM KOMBIT_A_COPENHAGEN.RAW.CITIZENS c CROSS JOIN (SELECT EJENDOMSTYPE FROM EJENDOM_TYPES ORDER BY RANDOM() LIMIT 1) et WHERE UNIFORM(0, 1, RANDOM()) < 0.05 LIMIT 5000;
INSERT INTO KOMBIT_A_AARHUS.RAW.EJENDOMME SELECT UUID_STRING(), 'MAT-AAR-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CPR_NUMMER, c.ADRESSE, c.POSTNUMMER, c.BY_NAVN, et.EJENDOMSTYPE, FLOOR(UNIFORM(500000, 15000000, RANDOM())), FLOOR(UNIFORM(50, 400, RANDOM())), 'AARHUS', CURRENT_TIMESTAMP() FROM KOMBIT_A_AARHUS.RAW.CITIZENS c CROSS JOIN (SELECT EJENDOMSTYPE FROM EJENDOM_TYPES ORDER BY RANDOM() LIMIT 1) et WHERE UNIFORM(0, 1, RANDOM()) < 0.05 LIMIT 5000;
INSERT INTO KOMBIT_A_ODENSE.RAW.EJENDOMME SELECT UUID_STRING(), 'MAT-ODE-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CPR_NUMMER, c.ADRESSE, c.POSTNUMMER, c.BY_NAVN, et.EJENDOMSTYPE, FLOOR(UNIFORM(500000, 15000000, RANDOM())), FLOOR(UNIFORM(50, 400, RANDOM())), 'ODENSE', CURRENT_TIMESTAMP() FROM KOMBIT_A_ODENSE.RAW.CITIZENS c CROSS JOIN (SELECT EJENDOMSTYPE FROM EJENDOM_TYPES ORDER BY RANDOM() LIMIT 1) et WHERE UNIFORM(0, 1, RANDOM()) < 0.05 LIMIT 5000;
INSERT INTO KOMBIT_A_AALBORG.RAW.EJENDOMME SELECT UUID_STRING(), 'MAT-AAL-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CPR_NUMMER, c.ADRESSE, c.POSTNUMMER, c.BY_NAVN, et.EJENDOMSTYPE, FLOOR(UNIFORM(500000, 15000000, RANDOM())), FLOOR(UNIFORM(50, 400, RANDOM())), 'AALBORG', CURRENT_TIMESTAMP() FROM KOMBIT_A_AALBORG.RAW.CITIZENS c CROSS JOIN (SELECT EJENDOMSTYPE FROM EJENDOM_TYPES ORDER BY RANDOM() LIMIT 1) et WHERE UNIFORM(0, 1, RANDOM()) < 0.05 LIMIT 5000;
INSERT INTO KOMBIT_A_ESBJERG.RAW.EJENDOMME SELECT UUID_STRING(), 'MAT-ESB-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM())::STRING, 8, '0'), c.CPR_NUMMER, c.ADRESSE, c.POSTNUMMER, c.BY_NAVN, et.EJENDOMSTYPE, FLOOR(UNIFORM(500000, 15000000, RANDOM())), FLOOR(UNIFORM(50, 400, RANDOM())), 'ESBJERG', CURRENT_TIMESTAMP() FROM KOMBIT_A_ESBJERG.RAW.CITIZENS c CROSS JOIN (SELECT EJENDOMSTYPE FROM EJENDOM_TYPES ORDER BY RANDOM() LIMIT 1) et WHERE UNIFORM(0, 1, RANDOM()) < 0.05 LIMIT 5000;

--------------------------------------------------------------------------------
-- COPY DATA TO PATTERN C (dbt) DATABASE
--------------------------------------------------------------------------------

INSERT INTO KOMBIT_C_DBT.RAW.CITIZENS SELECT * FROM KOMBIT_A_COPENHAGEN.RAW.CITIZENS UNION ALL SELECT * FROM KOMBIT_A_AARHUS.RAW.CITIZENS UNION ALL SELECT * FROM KOMBIT_A_ODENSE.RAW.CITIZENS UNION ALL SELECT * FROM KOMBIT_A_AALBORG.RAW.CITIZENS UNION ALL SELECT * FROM KOMBIT_A_ESBJERG.RAW.CITIZENS;
INSERT INTO KOMBIT_C_DBT.RAW.SAGER SELECT * FROM KOMBIT_A_COPENHAGEN.RAW.SAGER UNION ALL SELECT * FROM KOMBIT_A_AARHUS.RAW.SAGER UNION ALL SELECT * FROM KOMBIT_A_ODENSE.RAW.SAGER UNION ALL SELECT * FROM KOMBIT_A_AALBORG.RAW.SAGER UNION ALL SELECT * FROM KOMBIT_A_ESBJERG.RAW.SAGER;
INSERT INTO KOMBIT_C_DBT.RAW.YDELSER SELECT * FROM KOMBIT_A_COPENHAGEN.RAW.YDELSER UNION ALL SELECT * FROM KOMBIT_A_AARHUS.RAW.YDELSER UNION ALL SELECT * FROM KOMBIT_A_ODENSE.RAW.YDELSER UNION ALL SELECT * FROM KOMBIT_A_AALBORG.RAW.YDELSER UNION ALL SELECT * FROM KOMBIT_A_ESBJERG.RAW.YDELSER;
INSERT INTO KOMBIT_C_DBT.RAW.EJENDOMME SELECT * FROM KOMBIT_A_COPENHAGEN.RAW.EJENDOMME UNION ALL SELECT * FROM KOMBIT_A_AARHUS.RAW.EJENDOMME UNION ALL SELECT * FROM KOMBIT_A_ODENSE.RAW.EJENDOMME UNION ALL SELECT * FROM KOMBIT_A_AALBORG.RAW.EJENDOMME UNION ALL SELECT * FROM KOMBIT_A_ESBJERG.RAW.EJENDOMME;

--------------------------------------------------------------------------------
-- REFRESH DYNAMIC TABLES
--------------------------------------------------------------------------------

ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_CITIZENS REFRESH;
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_SAGER REFRESH;
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_YDELSER REFRESH;
ALTER DYNAMIC TABLE KOMBIT_A_AGGREGATED.DYNAMIC_TABLES.DT_ALL_EJENDOMME REFRESH;
