-- ============================================================================
-- KOMBIT Demo: Warehouses for Cost Attribution
-- Per-municipality warehouses enable accurate cost tracking
-- ============================================================================

USE ROLE SYSADMIN;

-- Municipality Warehouses
CREATE OR REPLACE WAREHOUSE KOMBIT_COPENHAGEN_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Copenhagen municipality workloads';

CREATE OR REPLACE WAREHOUSE KOMBIT_AARHUS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Aarhus municipality workloads';

CREATE OR REPLACE WAREHOUSE KOMBIT_ODENSE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Odense municipality workloads';

CREATE OR REPLACE WAREHOUSE KOMBIT_AALBORG_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Aalborg municipality workloads';

CREATE OR REPLACE WAREHOUSE KOMBIT_ESBJERG_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Esbjerg municipality workloads';

-- Grant access to roles
USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE KOMBIT_COPENHAGEN_WH TO ROLE KOMBIT_COPENHAGEN_ROLE;
GRANT USAGE ON WAREHOUSE KOMBIT_AARHUS_WH TO ROLE KOMBIT_AARHUS_ROLE;
GRANT USAGE ON WAREHOUSE KOMBIT_ODENSE_WH TO ROLE KOMBIT_ODENSE_ROLE;
GRANT USAGE ON WAREHOUSE KOMBIT_AALBORG_WH TO ROLE KOMBIT_AALBORG_ROLE;
GRANT USAGE ON WAREHOUSE KOMBIT_ESBJERG_WH TO ROLE KOMBIT_ESBJERG_ROLE;

-- Admin gets all warehouses
GRANT USAGE ON WAREHOUSE KOMBIT_COPENHAGEN_WH TO ROLE KOMBIT_ADMIN;
GRANT USAGE ON WAREHOUSE KOMBIT_AARHUS_WH TO ROLE KOMBIT_ADMIN;
GRANT USAGE ON WAREHOUSE KOMBIT_ODENSE_WH TO ROLE KOMBIT_ADMIN;
GRANT USAGE ON WAREHOUSE KOMBIT_AALBORG_WH TO ROLE KOMBIT_ADMIN;
GRANT USAGE ON WAREHOUSE KOMBIT_ESBJERG_WH TO ROLE KOMBIT_ADMIN;
